### ISSUE TITLE
feature request solar noon on widget

### ISSUE THREAD

**Issue by nutpantz** [forrestguice/SuntimesWidget#102]
It would be nice to see solar noon on the widget as an option.

**Comment by forrestguice** [comment]
Hi. The functionality is there but it looks clumsy. You can select "Solar Noon" from a widget's "general settings", causing the noon time to be displayed in both the rise and set fields (like I said, clumsy). So there is lots of room for improvement here. 

We can fix it to use just one field, show the noon icon, and use the right label. Is this what you had in mind?

**Comment by nutpantz** [comment]
I was hoping for a option for a 3rd line under tomorrow will be 3 mins shorter.
Something like
Solar noon at 12:45 pm
If the option to show it is checked.
Maybe even an option to replace daily time difference.

**Comment by nutpantz** [comment]
Even to be able to have a second widget with solar noon and maybe the next solstice date would even be very nice.

**Comment by nutpantz** [comment]
Even to be able to have a second widget with solar noon and maybe the next solstice date would even be very nice.
I know I can have just a single widget with only solar noon but I would like a little more info on the widget for the real estate used.

**Comment by forrestguice** [comment]
rgr that. I've got a much better idea now. 

An option to either add a third line, or replace the second line, or both. I like the idea of replacing the time difference (which doesn't seem all that useful to me, given the way the underlying libraries are rounding to the minute).

A completely separate noon widget is doable too, and pairing it w/ solstice info is an interesting idea. A separate solstice widget is already in the works. I'll need to (re)think how to best use the space. I had considered going as far as adding a 4x4 widget that displays the entire table.

**Comment by nutpantz** [comment]
While I don't use the shorter next day info very often, being a information junkie I like knowing, and have used the app and the info to annoy small children letting them know how much less time they have to get things done tomorrow.
4x1 or 4x2 with options selectable info shown would be my preferred size, even with all info shown.
But I wait with patience for updates with whatever features you create.

**Comment by forrestguice** [comment]
ok, I've added some options, "show noon" and "show comparison", and a new field to the layout. There are a few ways  I could change the layout but I think for now I'm just going to settle on..

    [title]
    [rise] [set]
    [noon]
    [comparison]

![screenshot_2017-11-07-14-02-07](https://user-images.githubusercontent.com/10246147/32517834-dd7385bc-c3c4-11e7-900d-f82d324cc566.png)

We can revisit that order later, or maybe add a "1x2 layout" option (similar to the existing "1x1 layout" option).

**Comment by nutpantz** [comment]
That looks nice, the only suggestion ok could make is have solar noon over sunrise and sunset.
I just think it would look better, like a pyramid..

But that's me.

**Comment by forrestguice** [comment]
hehe, its a toss up in my mind. 
I've stared at it every which way and can't decide.

![screenshot_2017-11-07-14-41-15](https://user-images.githubusercontent.com/10246147/32519434-f7578050-c3c9-11e7-8ecd-8626474142fe.png)

we can go with this instead. I'll leave it up to you.

**Comment by nutpantz** [comment]
I like that, but that's today.
Never leave it up to me.
You will never hear the end of it.
I respect the choice of the developer..
If I was better I would learn to code and put myself to task

**Comment by nutpantz** [comment]
Can't wait to see the update on fdroid
