### ISSUE TITLE
Feature request: bar widget

### ISSUE THREAD

**Issue by japhir** [forrestguice/SuntimesWidget#107]
Hi! I really like the app, and would love to be able to see the pretty bar as a widget on my home screen. Might be a nice feature?

**Comment by forrestguice** [comment]
Hi. I assume you mean the stacked bar graph that shows at the bottom of the app. I hadn't considered making this a widget, but I agree it would make a nice feature. Thanks for the suggestion.

**Comment by japhir** [comment]
Exactly!

**Comment by forrestguice** [comment]
It's now on F-Droid (so closing this issue as done). Thanks again for suggesting this feature. It led to a bunch of general improvements in theming the widgets.
