### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#12]
Ahoi!
First of all: Thank you very, **very** much for this app. I had a widget for sunrise/-set on my whishlist for months, now I found it on F-Droid.

I want to contibute a german translation. It seems that you there is no internationalisation yet, how can I help you without coding in java?

Also there is a file named app/src/main/res/values/styles.xml~, are you using emacs? ;-)

**Comment by forrestguice** [comment]
awesome. I'm really glad its useful for you. :)

I'm reading about the process here https://developer.android.com/guide/topics/resources/localization.html and will try to start working on it over the next week. I've tried to be consistent about pulling all strings into strings.xml so changes to the java shouldn't be necessary, but we'll see.

Optimistically, I think we just need to add a `values-de/strings.xml` and rebuild the app to get it into german. Unfortunately that strings.xml file isn't really as organized as its may appear - definitely a lot of work involved translating it. I'll try to clean it up by tagging the values that shouldn't be translated (and the other recommendations from the guide).

also, that `styles.xml~` definitely doesn't belong there - I'm not sure how let that scat file into the repo. I switched over to using Android Studio now, but I'm a `vi` guy, and it leaves those `things~` everywhere. ;)

**Comment by forrestguice** [comment]
ee351d4aa279fb12f809ad6d31925716dcf3b420

**Comment by forrestguice** [comment]
Support for localization is now in v0.1.1; thank you HerHde for getting things started with the translation to german. :)

Other translations are very welcome; if you're reading this and want to add a translation, please add an issue (similar to #15) and submit a merge request.
