### ISSUE TITLE
feature request : blue and golden hour

### ISSUE THREAD

**Issue by NicolasDesvignes** [forrestguice/SuntimesWidget#127]
Hi,
I love your app, and it'll perfect if you can add those features, watch the time of blue and golden hour (usefull in photography)
Thanks a lot

**Comment by forrestguice** [comment]
I will close this item when I tag the release. With any luck it will be in F-Droid by the end of next week. 

There is probably room for improvement - add another issue to the tracker if you think of anything.

**Comment by NicolasDesvignes** [comment]
Thank you for the feature add!
