### ISSUE TITLE
request feature, solstice tracking

### ISSUE THREAD

**Issue by nutpantz** [forrestguice/SuntimesWidget#13]
I love your app
I have been using a outdated app for years
It's nice to see a new app being developed
I would love to see a feature to track
Summer and winter solstice (longest and shortest days of the year)
maybe even a count down between solstice widget option

Keep up the great work.
I get your app from fdroid.It's nice to see it there.

**Comment by mirabilos** [comment]
Please also track the equinoctēs, not just the solstices.

Thanks!
