### ISSUE TITLE
release apk distribution

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#136]
I think I'm going to provide compiled apks for releases going forward (starting w/ v0.6.0). The apk will be signed with my Google Play key (and won't match the one signed by fdroid). I don't intend to distribute the apk through Google Play (but should I choose to in the future those signatures will match).

The reason.. The fdroid build/update process seems to be failing a lot recently. Its a known issue for awhile and they are working to resolve it. ...but these last few build cycles I think the process failed before suntimes got its turn to build (a failing build w/ empty log). The delay between tagging a release and having it show up in the repo (anywhere from a week to three or more) is a little frustrating, especially given the quick turnaround in the past (a day or two).

I'm actually confident these issues are only temporary, but moving forward I think it also makes sense to self-publish the apk, so that its available for immediate testing (and other feedback).

**Comment by JonnyTech** [comment]
Well, @IzzySoft has a F-Droid repo (https://apt.izzysoft.de/fdroid/repo) where he hosts open-source apk's that have been built by the developer. Maybe get it added there and those of us who have that repo added will see your builds in the F-Droid client.

**Comment by IzzySoft** [comment]
@JonnyTech always be [welcome to ask](https://gitlab.com/IzzyOnDroid/repo/issues) :wink: Though I have my concerns towards the same package_id being available via the main repo and mine, while using different signatures – that might confuse users. However: it could use a slightly modified package name so the two don't collide – in which case I'd see no issue with that. A different approach would be having the F-Droid build switch to "reproducible build" (i.e. while they still building themselves, the resulting APK would be matched against yours and, if successful, yours would go to their repo – so no more signature collisions).

**Comment by JonnyTech** [comment]
@IzzySoft, noted - sorry!

**Comment by IzzySoft** [comment]
@JonnyTech no need to be sorry. The tracker is rather new, so you might not yet have noticed. As pointed out: with the details clarified, feel free to file an issue (and link to the one of the app you want listed if there is one open and you think it's helpful).

**Comment by forrestguice** [comment]
thanks @IzzySoft. This gives me something to think about. The first option (modifying package id for self published apks) seems easiest to me, but "reproducible builds" is very appealing. I think distributing the same apk through multiple channels is a win.

For the time being I will hold off (and see how things shake out). My preference is to do nothing (lazy). ;)

**Comment by IzzySoft** [comment]
@forrestguice No prob. If you need me, you know where to find me. Whichever approach you want to take, I gladly accept your app in my repo (as long as we avoid above described "confusion"). Offered the same to Gadgetbridge a year ago (for the same reason you brought up) – as they don't build themselves at all, they still need to figure about the signing key and who has access to it. So take your time :wink:

**Comment by nutpantz** [comment]
I would just leave it to the user to figure out which one to use.generally I get what I can from fdroid but I grab a few things from Google play when there is no other way. 
Yes it can be a hassle when fdroid is way behind on updating.  
But if you host your own apk. that will work.
Hopefully fdroid will fix their issues.

**Comment by IzzySoft** [comment]
> I would just leave it to the user to figure out which one to use.

Sure. But for a choice to be made an option must be there :wink: And with reproducible builds, the user can even re-consideddr without re-installing.

And yes, I as well hope those (not that infrequent) issues with their build-server will be solved soon. I doubt they're happy about that themselves!

**Comment by mirabilos** [comment]
Any chance to retrigger the F-Droid build?

Do (you know about whether) they have a bugreport about that you can link?

**Comment by forrestguice** [comment]
Sorry but I don't have any control over the fdroid build. :(

Basically the metadata was updated over 3 weeks ago (https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.forrestguice.suntimeswidget.txt) but there haven't been any attempts to build it (https://f-droid.org/wiki/page/com.forrestguice.suntimeswidget/lastbuild_16) - I think the empty log indicates the build process is failing before suntimes even gets a turn. I don't have any reason to believe the build itself needs to be fixed (its identical to the previous 0.5.1 build which succeeded).

Their was a discussion about it here: https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195 .. but the forums were taken offline by the meltdown/spectre updates and only recently back online - there isn't any news there. So its not a new problem, but I also don't think its ever been this bad.

I think they have a backlog of ~150 failed builds (https://f-droid.org/wiki/page/Category:Apps_with_failing_builds), a large number of them in the same situation as suntimes (failing build, missing log). I also see issues being filed in the tracker, like this one; https://gitlab.com/fdroid/fdroiddata/issues/1082, or this one https://gitlab.com/fdroid/fdroiddata/issues/1079. ..but so far all of these issues have been answered the same way.. the build process is failing and there no eta. 

For that reason I've held off opening my own issue but maybe this is an occasion where it pays to be a "squeaky wheel" - I kind of doubt it :\ There is also this https://gitlab.com/fdroid/fdroidserver/issues/441 .. I can feel the frustrating in that one.  Other than monitoring https://f-droid.org/wiki/index.php?title=Special:RecentChanges&limit=500&hidebots=0, there isn't any insight into whats going on..

So I'm not sure what is to be done. If I tag another release I think the metadata will be updated, but then I'll be waiting on two failing builds instead of one. I don't think there is a way for me to retrigger it on my own (and not sure the maintainers even have that capability).. ugh :(

**Comment by IzzySoft** [comment]
I'm afraid there are at least 2 reasons behind why Suntimes wasn't yet built:

* the Maintainer crew being understaffed, and
* the build server giving troubles.

There was no new app build within the last 5 days, before that it was just 2 new apps, and before that the build server was reportedly "broken". So in the past month, just 6 new apps have been added. For apps that already have been in the repo, it looks comparable: no updates within the past 5 days, then 61 updates about a week ago (a single bulk run, it seems), 8 updates the week before that, 48 updates within the 2 weeks before that. So updates of existing apps seem to have faired better – which points to the crew being understaffed (those apps already were configured and set up for automated updates, while new apps need manual care at first).

To give you a pointer of where I tracked that: I've used the filters of [my repo browser](https://apt.izzysoft.de/fdroid/index.php?repo=main), where I recently also added F-Droid's main and archive repos, Guardian and some more – mainly as Archive, Guardian & Co don't offer a way to browse them (except via the F-Droid client), and as I wanted to be able to see what new apps F-Droid had added recently (which on their newly designed website is reduced to 3 entries – my browser has no such limitation).

**Comment by forrestguice** [comment]
https://gitlab.com/fdroid/fdroidserver/issues/449 .. I can't help but lol. It seems the build "queue" is actually a stack (and we were stuck at the bottom). The last tag (0.6.1), made a week ago, was picked up by f-droid and built yesterday. It should be in the repo next update. Also some useful info (last runs) now posted to https://f-droid.org/wiki/page/Main_Page.

**Comment by forrestguice** [comment]
It seems the f-droid build process is running a lot better now. I tagged 0.6.2 a few days ago, and yesterday F-Droid detected it, built it, and today its published. Very quick. :)

I'll be closing this issue in the next week - the plan is 'no plan'. I am going to continue building apks (and putting them in the release section) but I won't be looking to publish in other repos/stores. Moving forward it might be worthwhile to try switching on "reproducible builds" on the F-Droid end (I'm actually not sure what this involves). 

@IzzySoft I appreciate your offer to include the app in your repo - eventually I want to do that, and I think the best way is w/ reproducible builds. I don't want to mess around w/ the package id (as of yet), not only because it complicates things, but because changing it introduces a strong temptation (for me) to start "rebranding" the app _.oO(...changing the packageid? to what exactly, and why stop there)_.

**Comment by IzzySoft** [comment]
@forrestguice Be welcome to ping me if need arises :wink:

**Comment by PacoBell** [comment]
Why'd you stop (regularly) building Release APKs? F-Droid build is now 9 days behind the latest release and that [alarm dialog regression](https://github.com/forrestguice/SuntimesWidget/commit/7892dd5271ad7998835d2bc8532d84af6ff22507) is quite the pain point right now.

**Comment by forrestguice** [comment]
Please be patient.. Releases are usually available within a week. I'm sorry to hear F-Droid is having some trouble this time around, however the app was [successfully built](https://monitor.f-droid.org/builds/log/com.forrestguice.suntimeswidget/90) a few days ago, so it will probably be available any day.

I don't make regular release builds, never have, and don't plan to. Supposing I did it wouldn't be signed with the same signature, would replace your previous apk (wiping user data), and so not as helpful as you might think. Same result as building it yourself..
