### ISSUE TITLE
No Data Source

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#14]
Ahoi,
in the general settings, there is only a `%s` "selected" as the `Data Source` by default.

Greetings
HerHde

**Comment by forrestguice** [comment]
confirmed. I had forgotten, but there is a bug here. I think its only cosmetic.

The `%s` comes from `preference_general.xml` (but probably belongs in `strings.xml`) and is supposed to be replaced automatically by the PreferenceActivity with the current value .. but for various reasons the setting has no value by default, and the ListPreference doesn't know the default (or what to provide as a substitution in that case).

**Comment by forrestguice** [comment]
fix appears in v0.1.1
