### ISSUE TITLE
Azimuth and elevation angle

### ISSUE THREAD

**Issue by lufticus** [forrestguice/SuntimesWidget#169]
I would like the app to show azimuth and elevation angles of the current position of the sun at the location as well as of sunrise and sunset. A bonus is the shadow length.

**Comment by MenoData** [comment]
See the [API](http://time4j.net/javadoc-en/net/time4j/calendar/astro/SunPosition.html) of my lib Time4J/A (is a project dependency here). Two input parameters are necessary, the moment (for example current time) and the geographical location.

About the shadow length, the height of the relevant object (for example a human being or a building) in meters (or feet for US) is necessary, then a simple trigonometric calculation can be done using the elevation angle of sun.

**Comment by forrestguice** [comment]
Thanks for the suggestion. I will add this to the upcoming release v0.8.0 (a few weeks out).

@MenoData As always thanks for your help :) I was able to implement this w/out any trouble (btw that work kept in [branches/sunposition](https://github.com/forrestguice/SuntimesWidget/tree/sunposition)).

**Comment by forrestguice** [comment]
This is now on F-Droid (so closing this issue). Thanks again for the suggestions.

btw, "shadow length" didn't make it into this release. I am going to open a separate issue for it. This is easy enough to do, but I'm a little uncertain about the best approach for the UI. It would help to know more about the specific use cases. How is shadow length generally used? i.e. is it mainly for calibrating/creating sundials?
