### ISSUE TITLE
Indicate skipped dusks

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#17]
Ahoi,
depending on your latitude, some dusks/twilights don't occur, like [up in the north](https://en.wikipedia.org/wiki/Midnight_sun#White_Nights). The english Wikipedia has [some Information](https://en.wikipedia.org/wiki/Twilight#Duration) about this, but your App already correctly shows no Values for e.g. my position:
![photo_2016-07-11_16-15-23](https://cloud.githubusercontent.com/assets/7630662/16733777/3fb50e2c-4783-11e6-97ed-80d4e951017a.jpg)

Could you please set this empty values to `none` or something, so it doesn't seem broken?

Greetings
~HerHde

**Comment by forrestguice** [comment]
fix appears in v0.1.1
