### ISSUE TITLE
[Feature request] World map view with current day and night

### ISSUE THREAD

**Issue by beriain** [forrestguice/SuntimesWidget#174]
Hi! First of all, thank you for developing such a great app.

I wanted to suggest a feature request. It would be great to have a world map overview with current day and night, both in app and as widget. I mean something like this: [https://github.com/GChristensen/sunligth-world-map-gadget](https://github.com/GChristensen/sunligth-world-map-gadget)

What do you think?

**Comment by forrestguice** [comment]
> Hi! First of all, thank you for developing such a great app.

Thank you! I'm really glad its useful for you. :)

> I wanted to suggest a feature request. It would be great to have a world map overview with current day and night, both in app and as widget. I mean something like this: https://github.com/GChristensen/sunligth-world-map-gadget

> What do you think?

I think I've been unintentionally creating a world clock all this time. lol.  :)
My initial reaction is that its beyond the intended scope of the app, but...

That world-map-gadget looks pretty neat. I can definitely imagine the app doing this - a simple map displayed from a dialog, or from a widget - but nothing too heavy (that would replace a full featured "world clock" app).

Thanks for the suggestion.

**Comment by forrestguice** [comment]
![image](https://user-images.githubusercontent.com/10246147/43690393-efac5cd0-98bd-11e8-9b0f-f038496aa3ab.png)

Of course colors can be changed (maybe to make it look like the ore map from KSP). There is also a "Blue Marble" appearance. I'm tagging 0.9.0 soon - it should be on F-Droid next week.

I think there is still potential here, and a few rough edges to work out. I'm going to leave this issue open to collect any feedback. Hopefully this is close to the mark, its was a lot of fun to code. :)
