### ISSUE TITLE
Application crashes when name of user defined location contains an apostrophe

### ISSUE THREAD

**Issue by jcp-sd** [forrestguice/SuntimesWidget#177]
I was having a problem with the application crashing whenever I would tap on the location "push pin". It took a little bit of detective work, but I think this is because the user defined location name I had entered had an apostrophe in it (e.g. "John's House" without the double  quotes).

The only way to recover was to delete all the app data (settings->apps->suntimes->delete data). When I enter the user defined location name again without an apostrophe, then everything is fine. When I enter a location name with an apostrophe, it crashes when you go back into the location settings. 

I'm guessing that an apostrophe or single quote needs to be escaped before storing the string internally or something like that. Everything else seems to be working just fine for me.

**Comment by forrestguice** [comment]
Bug confirmed, I am able to reproduce the problem as described. 
Thank you for tracking this down and reporting this. 

As you have guessed, the exception is coming from a SELECT on the sqlite db (but curiously not from the INSERT a few lines before). I'll have to take a much closer look here.

**Comment by forrestguice** [comment]
This should be fixed in 0.7.3 (update now available on F-Droid).
Thanks again for taking the time to report. :)
