### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by harmonic-trader** [forrestguice/SuntimesWidget#179]
Hello. I think your projecta needs a new logo and I can do this if you want?

**Comment by forrestguice** [comment]
Hello :) Thanks for taking interest in the project. I can appreciate your desire to contribute. I took a peek at your activity and see you've made similar offers to other foss apps. That's awesome.

I think `need` is a strong word though. I am actually happy with the design of the icon, and not currently looking to replace it.
