### ISSUE TITLE
Display Moon information on main screen

### ISSUE THREAD

**Issue by sphh** [forrestguice/SuntimesWidget#183]
At the moment I have to add a widget if I want to see some information about the moon, but I don't need this information that often to justify using this precarious space.

Would it be possible to display the moon information on the main screen?

**Comment by forrestguice** [comment]
Good news, I've been working on this over the past week and its very close to ready - the moontimes branch has that code. The plan is to merge that into master sometime in the next week, and then tag it v0.8.0. I'm guessing it will be up on F-Droid before the next new moon.

relates to #52

**Comment by sphh** [comment]
Brilliant!! Thanks.

**Comment by forrestguice** [comment]
The update is now on F-Droid (and a little quicker than I expected).

**Comment by sphh** [comment]
Thanks!!!
