### ISSUE TITLE
Enhancement: Mid align sun position widget labels

### ISSUE THREAD

**Issue by erdihu** [forrestguice/SuntimesWidget#188]
Hi,
Sun position widget labels stayed left aligned after the widget has been resized. Is it possible to mid align the labels? Alternatively, an option to choose the alignment would be practical.
Thank you.

**Comment by forrestguice** [comment]
sure, this can be done. I'm assuming you are talking about this widget https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/res/drawable-nodpi/sunposwidget0_3x1_preview.png 

I think one way to mid-align would be to right anchor the last three labels (w/ the first two labels anchored to the left and an expandable space in the middle). Another way would be to center align all five labels (keeping the current space between each label). 

Which appearance did you have in mind?
