### ISSUE TITLE
shadow length

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#189]
Add "shadow length" to the sun position information (see also #169).

This enhancement requires providing the object's height somehow.. (and implies support for localized units; ft vs meters, etc).

One approach is to confine the functionality to a separate dialog box that accepts height, and displays the current shadow length, length at noon, etc (for the configured date).

Another approach is to integrate the functionality into the sun position / lightmap dialog. Instead of providing the height each time, its configured once in settings (and set to something arbitrary by default, like 6ft).

**Comment by MenoData** [comment]
Just to note: I have implemented the necessary calculation in the latest Time4A-version, see also the API of [SunPosition](http://time4j.net/javadoc-en/net/time4j/calendar/astro/SunPosition.html#getShadowLength-double-)
