### ISSUE TITLE
Update German localisation

### ISSUE THREAD

**Issue by wolkenschieber** [forrestguice/SuntimesWidget#191]
The German translations contain numerous untranslated texts.

**Comment by forrestguice** [comment]
Indeed, it hasn't been updated in some time (https://github.com/forrestguice/SuntimesWidget/wiki/Translations). Thank you for taking the initiative.

**Comment by HerHde** [comment]
Thanks @wolkenschieber, I've tried to continue the translation some weeks ago, but got stuck with the terminology, especially with the local mean time stuff.
Looks good ;-)
