### ISSUE TITLE
Usable hours anomaly

### ISSUE THREAD

**Issue by gadgetguy08** [forrestguice/SuntimesWidget#209]
Recently when travelling to the far north, I noticed the number of usable hours showed 1 minute when, in fact, the sun never set.
Trying to attach a screen shot, but not able to.

**Comment by forrestguice** [comment]
Thanks for reporting. A screenshot is always appreciated, but I just tried to reproduce this, and I think I know whats going on.

The code that returns the duration string is a little dumb. When there isn't anything to display, and configured to omit seconds, the rule is to display 1m .. I swear that made sense at some point, although I'm having trouble remembering how..

Anyhow, I think this is an easy fix, but it wouldn't surprise me if there were other bugs like this one.

**Comment by forrestguice** [comment]
This should be better behaved w/ v0.8.4. The update is now on F-Droid.
