### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by FTno** [forrestguice/SuntimesWidget#210]
In the norwegian translation I changed the order of the date strings for solstice/equinox to display (for example) '21. june, 12:07' instead of 'june 21, 12:07'.
After startup of Suntimes it displays the format wrongly as 'june 21, 12:07', but after closing the app with the back button and starting it again, it displays correctly '21. june, 12:07'. If I remove Suntimes from recent apps and start again it's back to the wrong format 'june 21, 12:07'.

**Comment by forrestguice** [comment]
Thank you. I'm able to reproduce this. 
btw I appreciate the details provided. Good bug report :)
