### ISSUE TITLE
app crash on polar regions when no rise/set events reported

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#212]
The app crashes (`NullPointerException`) when trying to schedule an update (setPartialUpdateAlarm) if the calculator implementation reports no rise/set events. This is a common occurrence in polar regions, however the bug goes unnoticed because the default calculator (time4a-noaa) is unaffected (masks the bug). Using the `sunrisesunsetlib` or `ca.rmen.sunrisesunset` calculators with far north or south latitudes will cause the app to crash.

**Comment by forrestguice** [comment]
the reason..
It seems the time4a calculators always return a noon time (midday) even when the sun never rises, which avoids the bug. In this case the other calculators don't report noon, so the set of events is empty and `findNextEvent` falls back to its default (sunrise, which doesn't occur and so is null).

The bug was introduced in v0.7.4 with the enhanced update functionality (i.e. "app now automatically advances to next note").

**Comment by MenoData** [comment]
Notice about api-usage ("It seems the time4a calculators always return a noon time (midday) even when the sun never rises or sets,"):

`public ChronoFunction<CalendarDate,Moment> transitAtNoon()`

> Calculates the moment of noon at the location of this instance (solar transit). 
> 
> Note: The transit time does not tell if the sun is above or below the horizon. 
> Returns:noon function applicable on any calendar date
