### ISSUE TITLE
Option to select 12h/24h

### ISSUE THREAD

**Issue by erdihu** [forrestguice/SuntimesWidget#22]
It seems only 12h format is supported right now. Can 24h format be added into the settings? My phone locale settings is set to 24h by default.

**Comment by forrestguice** [comment]
It should respect the "Use 24-hour format" setting from `System Settings -> Date & Time`, although some locales are 24hr only (in which case I think the option is disabled). 

If the rest of your phone is showing 24hr time except the app, then definitely a problem.. Can I get a screenshot? Which locale are you using? I will try to reproduce it.

**Comment by erdihu** [comment]
Found the problem after a second look. I though it was showing my city name under the current time but I realised it is in fact the timezone. Thus I missed that coordinates was wrong, hence the sunrise/sunset times. It explains the odd times. Sorry for confusion. :)

**Comment by forrestguice** [comment]
I'm glad there is no bug, but thanks for making the report :) I gain some insight anyway.

If I understand correctly, it only looked like it was displaying 12hr time, because the times were something crazy looking (like sunset at 09:00 in the morning). I think the confusion is because default coordinates are at my location (northern az), while timezone defaults to system setting, so you see some crazy looking (yet accurate) times as a result of the timezone/location mismatch.

**Comment by JonnyTech** [comment]
Sorry to reopen this but I too am stuck in 12 hour format - is there an easy way to force 24 hour mode?

**Comment by forrestguice** [comment]
Right now this is set from System Settings, but if you are familiar w/ building android apps, you can force it easy by changing a line in the calendarTimeShortDisplayString method in SuntimesUtils.java (line 211; https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/java/com/forrestguice/suntimeswidget/SuntimesUtils.java#L211). 

Thinking it over, I'm willing to add an option to the app to force it, if thats useful - the app already allows overriding the locale so maybe there are situations where it is. What's your own 'use case'? At any rate (kinda slow), having this option in an fdroid build is at least a few weeks off.

**Comment by forrestguice** [comment]
@JonnyTech hey, I've uploaded a beta apk if you wanted to give this a test or don't want to wait for the release on fdroid (gonna be awhile). https://github.com/forrestguice/SuntimesWidget/blob/option-24hr/app/bin/suntimes-v0.3.1p0.apk

note: its built in release, signed with my key, and has the same version as the latest release on fdroid (10)... so you're probably going to have to uninstall before it lets you sideload it.

**Comment by JonnyTech** [comment]
Thank you very much, the beta works perfectly. I can change timezones and location yet the time format remains fixed to my preference. Nice one.
