### ISSUE TITLE
Add an option to change the language of application

### ISSUE THREAD

**Issue by verdulo** [forrestguice/SuntimesWidget#23]
Nuntempe mi tradukas la Suntimes aplikaĵon al la Pola (pl) lingvo, poste mi volos fari Esperantan (eo) tradukon. Ĉu vi povus aldoni agordon por ŝanĝi lingvon de programo? Tio estas grava precipe por Esperanto, ĉar ĝi ne povas esti elektita en Android kiel ĉefa lingvo de sistemo...

Now I'm translating the Suntimes app into Polish (pl) language, later I want to make translation into Esperanto (eo). Could you add setting to change program language? This is important especially for Esperanto, because it cannot be selected in Android as default system language...

**Comment by forrestguice** [comment]
added in v0.2.0
