### ISSUE TITLE
Truncated text in translations

### ISSUE THREAD

**Issue by FTno** [forrestguice/SuntimesWidget#254]
To translate the Add Theme page (Widgets) is very difficult because there is so little space available.
In english it's common to divide words (like sunset color instead of sunsetcolor), while in some other languages this is not common (like at least the nordic and german). English often has shorter words and expressions too.
This scarce space results in a lot of truncated text. A couple of examples are seen in the screenshot where this is what should have been displayed: "Måneoppgangsfarge:", "Månenedgangsfarge:", "Soloppgangsfarge:" and "Solnedgangsfarge:".

![screenshot](https://user-images.githubusercontent.com/16176811/47255489-442d9b80-d472-11e8-87f6-d6d07883d57e.png)

Using a lot of abbreviations could at least be a partial solution, but would not look pretty.

**Comment by forrestguice** [comment]
Fixed in v0.10.0, should be on F-Droid soon.
The layout still needs some work but the labels should be readable now.
