### ISSUE TITLE
Feature request : Moon Apogee and Perigee

### ISSUE THREAD

**Issue by johaziel** [forrestguice/SuntimesWidget#296]
Hi, 
Thanks for your work on this app who is so useful.
It could be very nice if you can add also moon apogee and perigee informations.
You can find information here 
https://www.timeanddate.com/astronomy/moon/lunar-perigee-apogee.html
or 
https://www.fourmilab.ch/earthview/moon_ap_per.html
and there is the calculator 
https://www.fourmilab.ch/earthview/pacalc.html and you can access to the [javascript](https://www.fourmilab.ch/earthview/pacalc.js) to get equation.
Regards
Jo

**Comment by forrestguice** [comment]
This has been added in v0.12.0 - its now available on F-Droid.

I want to apologize for taking so long to get to this - this work has actually been sitting around in a branch for some time.

I also want to thank @MenoData for adding this functionality to Time4J - proper recognition goes to him for making this feature possible.
