### ISSUE TITLE
Shadow length

### ISSUE THREAD

**Issue by shawn1thompson** [forrestguice/SuntimesWidget#331]
It would be nice to have the shadow length added as a notification or alarm when it is, for example, equal to the height of the object. Otherwise, thanks for the excellent work. I'm enjoying this app.

**Comment by Knusper** [comment]
I think more interesting would be a display of the sun's elevation.

**Comment by sjvudp** [comment]
I agree: Shadow length depends on the surface, too. Also shadow length will be a proportion anyway, so if you have the elevation in degrees (°), isn't the shadow length **L** = _object height_ divided by _tangens of the elevation_? (For the object being right up and the shadow surface being perpendicular to the object casting the shadow)
