### ISSUE TITLE
widget update

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#341]
moon widget ( 4 x 1) doesn't update automaticly , and i should open it and reconfigure it .

**Comment by forrestguice** [comment]
hrm I haven't observed this problem. I'll look for a possible cause and try to reproduce it, but the code that updates the 4x1 widget is actually the same that updates every other widget, so I would expect to see the same problem for the others.

Have you force closed the app at any point? This would cause the widget to stop updating. There are also few other similar scenarios that might cause the widget to lose its update timer.

Anyhow, if you go to `Settings -> Widgets` .. to open the widget list, this will trigger all widgets to reschedule their next update. This should cause the 4x1 widget to start behaving normally again.

**Comment by forrestguice** [comment]
Out of curiosity, was the widget badly out-of-date? Like it should have updated days ago? hours ago? There is also the issue of battery optimization on newer devices, but in that case the updates are deferred into batches, every 15 to 20 minutes.

**Comment by islam2hamy** [comment]
"Have you force closed the app at any point? "

 no

 "Out of curiosity, was the widget badly out-of-date? Like it should have updated days ago? hours ago?"

 days

 and i am using optimizing battery

 p.s : show time in the widget is disabled

**Comment by islam2hamy** [comment]
just to let you know it is now work good , and i am afraid it was my mobile problem ,let's close this for now .
