### ISSUE TITLE
Allow Scrolling Future and Past Days

### ISSUE THREAD

**Issue by VA1DER** [forrestguice/SuntimesWidget#352]
Currently when you open the app you see today's information with to option to flip over to see tomorrow's.  Not sure why it's currently limited to only seeing one day in the future, but it would be nice to be able to arbitrarily flip through days future and past

**Comment by forrestguice** [comment]
I agree this is how it should be. It has also been on my todo list for awhile. Its basically limited by its current implementation (using a ViewFlipper; probably needs to refactored to use a RecyclerView), and is something I've been putting off (for more interesting problems). I can try to get this done for the next minor release.

**Comment by forrestguice** [comment]
This enhancement is included in v0.12.0 - its now up on F-Droid.

In addition to fixing the main table, I've done the same for the solstice/equinox and moon phases. I'm pretty pleased with the result - this is a great enhancement. Thank you for taking the time to open this issue and helping me improve the app.
