### ISSUE TITLE
How to activate functions of alarm

### ISSUE THREAD

**Issue by Itsalltext** [forrestguice/SuntimesWidget#355]
![Screenshot_2019-08-22-13-30-33](https://user-images.githubusercontent.com/1583047/63522609-0158ac00-c4f9-11e9-9fd2-7000f179df70.png)
Hello Forrest,

first I like to thank you for providing the app with the great philosophy.

I installed the app from fdroid and start working with the Alarms, but as you see in the attachment the function of Set Type, Set Event, Set Offset, Set Location, Set Repeating, Override Time is disabled.

What must I do to enable the functions?

**Comment by forrestguice** [comment]
You will need to disable the alarm first, and then those functions should become enabled. 

The UI is still pretty clumsy in this regard. Changing these options essentially reschedules an already active alarm, but I made a decision to simplify the design (in the interest of making a first release). I think it should really allow changing options while enabled, so maybe its time to revisit this.
