### ISSUE TITLE
Layout problem when using the app in pt_BR

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#356]
With the latest version (`0.11.9 (4eae0176)`, which includes a Brazilian Portuguese translation) it's not possible to properly see the full sunset time anymore:

![](https://user-images.githubusercontent.com/982338/63852864-a5b27680-c96f-11e9-9583-0d62f4c20971.png)

**Comment by forrestguice** [comment]
I think last commit might fix it. 

I reviewed the layout (been awhile) and had forgotten how its pretty much been reworked to death. It is already possible to change its appearance by supplying different parameters for different screen sizes (defined in `values/table_res.xml`), but I discovered its also possible to use additional qualifiers and do this per-locale.

So the following resources have been added: 
* `app/src/main/res/values-pt-rBR/table_res.xml` (smallest screen)
* `app/src/main/res/values-pt-rBR-sw330dp/table_res.xml` (wider than 330dp)
* `app/src/main/res/values-pt-rBR-sw400dp/table_res.xml` (wider than 400dp)

For the smallest screensize the margins are practically eliminated and the heading fontsize reduced by 1. For slightly larger screens the margins are only reduced slightly (and fontsize restored to default), and for screens larger than that the appearance reverts to the default.

Its possible to shadow other values and tweak the appearance further, but the minor adjustments I just mentioned seem enough to get all the information back onto the screen.

**Comment by forrestguice** [comment]
If you'd like to test it, I'm very curious to see a screenshot. 

I've put a binary here; https://github.com/forrestguice/SuntimesWidget_beta/releases/tag/v0.11.9-fix356 (but its signed with a different key than the F-Droid release, so its necessary to remove one to install the other).

**Comment by naoliv** [comment]
With your new APK it seems good!
![Screenshot (29 de ago de 2019 22_19_03)](https://user-images.githubusercontent.com/982338/63986733-a6502780-caab-11e9-8451-2c6bdec432ce.png)

**Comment by forrestguice** [comment]
That's great news. :)
I found a similar issue with the Norwegian translation and applied the same fix.

I'll tag `v0.11.10` early next week. It should end up on F-Droid a few days after that.

**Comment by naoliv** [comment]
Great! Thanks a lot!

**Comment by forrestguice** [comment]
There was quite a bit of refactoring in v0.12.0, but layout fixes here should remain (hopefully no regressions).
