### ISSUE TITLE
Scrollview cropping issue. bug layout ux

### ISSUE THREAD

**Issue by Zappleberry** [forrestguice/SuntimesWidget#361]
This looks similar to issue #207 but I am getting it on all selection dialogs.

Below is the dialog for selecting when to have an alarm, but the visible part of the selection dialog and the actual dialog seem to have different sizes. To select blue hours I have to click above the visible dialog.

![Screenshot_20190911-094451](https://user-images.githubusercontent.com/26125594/64717776-8563db00-d48a-11e9-975e-3352d4d25328.png)

Here is one with the location selection dialog. I am not a android developer but it looks like the space allocated for the dialog is not the same as the space being drawn for it.

![Screenshot_20190911-095517](https://user-images.githubusercontent.com/26125594/64718127-37030c00-d48b-11e9-8128-b822b23c26df.png)

The "About" dialog/scrollview seems to be working fine.

When I go to check widgets, they work fine

Happening on a LG G8

**Comment by forrestguice** [comment]
Thanks for reporting this. I'll need to investigate further.

It looks like its happening in the dialogs that have a Spinner (drop down). I would be curious to see a screenshot of the "Set Time Zone" dialog when selecting from the user defined list.

I'm not sure I fully understand the symptoms, but those menus are positioned strangely.. I'm assuming the location list has only 2 entries - that menu should be centered on the spinner, not floating above the dialog. hrm.

**Comment by Zappleberry** [comment]
Whats happening with the "set time zone" is the drop down arrow flashes with a little white circle but the menu/dialog/spinner does not open.

I am having a bit of trouble capturing it because it need video recording.

The location spinner has 1 entries, if that helps.

**Comment by forrestguice** [comment]
ymmv 
https://github.com/forrestguice/SuntimesWidget_beta/releases/tag/v0.12.0-beta.1

**Comment by Zappleberry** [comment]
the 0.12.0beta1 release fixed this!

**Comment by forrestguice** [comment]
Nice! Thanks for testing this for me. It was great help.

It looks like v0.12.0 is now on F-Droid.
Just a reminder that you'll need to uninstall/reinstall if you want to receive updates from F-Droid (since the beta was signed by a different key).
