### ISSUE TITLE
full moon allarm/notification

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#365]
if i set alarm for full moon , with offset before 2d and 2h or more , the app crash.

**Comment by forrestguice** [comment]
yikes - thank you for reporting this so promptly. I'm looking at it now and seeing this too :\

**Comment by forrestguice** [comment]
I don't think `2d 2h` is coincidental, that is the time from now until next full moon. It would seem the scheduling algorithm is running an infinite loop - I observe the app freezing, followed by a force stop.

**Comment by forrestguice** [comment]
So far so good - I think this is fixed.
