### ISSUE TITLE
can't get location while GPS is working and has a fix

### ISSUE THREAD

**Issue by xandro0777** [forrestguice/SuntimesWidget#373]
Since some time the app thinks it can't get GPS even though GPS fix is displayed by other apps - it is also displayed in the notification line of my device thanks to SatSat.

My device is "slightly" affected by GPS week counter roll-over - it reports a wrong GPS time. Maybe there is some overzealous check somewhere triggered by this? All other apps (maps, web pages etc) work fine despite this.

**Comment by forrestguice** [comment]
Thanks for reporting this. I'll need some additional info (but also optimistic this is an easy fix).

How is the location configured? Is it set to "user defined" or "current (last known)"? I'll assume that its the same bad behavior for both.

Does changing the "GPS recent max age" (from Settings->Places) have any effect? There is in fact a check against the GPS time - it does sound like its throwing away all the results. I'm guessing that setting the max age to a larger value (a month) might be a workaround.

Does enabling "Passive Location" (from Settings->Places) have any effect? When enabled the app doesn't actively query the location, but instead uses the location retrieved by some other app (e.g. satstat). This is a shot in the dark - it won't make a difference if the GPS time is consistently wrong.

You mention "regression" - did this functionality work correctly at some point? Can you remember which version that was? The location handling code hasn't been modified in a long time (there  was some refactoring v0.12.0). A regression is certainly possible, but I'll assume this is actually a bug that's been lurking for awhile.

**Comment by forrestguice** [comment]
I'm reading about GPS week counter roll-over (https://space.stackexchange.com/questions/35362/what-is-gps-19-year-rollover-and-does-it-present-a-cybersecurity-issue). Wow this is very interesting! I wasn't aware of any of this.

It sounds like setting "recent max age" isn't the workaround I had hoped - I think it will be necessary to add a setting to disable the check entirely.

**Comment by xandro0777** [comment]
Enabling passive location apparently didn't help, neither setting max age.

As of regression.. the currently used location is a lake where I have been a few times during the summer and I remember looking at sunset time there setting that location and seem to remember that was most likely 2-3 months ago when sunset times were most interesting. So it was 99% sure after the Android rollover.

There is also a second Applee rollover on Nov 3 but I would be surprised if my Moto G had been affected by the Apple and not the other one..

Anyway.. right now my GPS clock displays a date like 2000-04-11T22:57 whereas device time is 2019-11-26T21:57 - note the one hour difference which could be time zone but perhaps also another quirk.

Maybe if you test the time modulo 1024 weeks it will still work?

**Comment by xandro0777** [comment]
Also realised.. the problem may be comparing device and GPS times? Because  https://en.wikipedia.org/wiki/Leap_second this might trigger further strangeness in the future.

**Comment by forrestguice** [comment]
> the problem may be comparing device and GPS times?

I think that's essentially it. `Location.getTime()` doesn't return a system time, it returns whatever timestamp was obtained from the location provider (GPS time, network time, etc), so its not a safe comparison. I think GPS time currently differs from UTC something like 18 seconds, and then there is this situation with devices not handling the rollover correctly.. ugh. 

The bug may be intermittent (depending on the location provider). It should actually work if the location originates from the network provider, failing when there isn't any service, or the device is configured to use GPS only.

I'm hoping its fixed for api17+ by calling `Location.elapsedRealtimeNanos` instead (reports time since boot), and comparing that against `SystemClock.elapsedRealtimeNanos()`.

**Comment by forrestguice** [comment]
I've put a binary here; https://github.com/forrestguice/SuntimesWidget_beta/releases/tag/v0.12.2-fix373 .. Its signed with a different key than the F-Droid release, so testing is actually a bit of a pain - its necessary to uninstall/reinstall, etc.

I'll probably tag v0.12.3 over the weekend (typically picked up by F-Droid within a week).

**Comment by xandro0777** [comment]
On November 27, 2019 9:27:54 PM GMT+01:00, Forrest Guice <notifications@github.com> wrote:
>> the problem may be comparing device and GPS times?
...
...
>I'm hoping its fixed for api17+ by calling
>`Location.elapsedRealtimeNanos` instead (reports time since boot), and
>comparing that against `SystemClock.elapsedRealtimeNanos()`.

seems the documentation has been misleading at times and there may be more surprises lurking. 

I think the power savings reusing last location for a relatively rare manual gps lookup are completely uninteresting.

So the most robust approach might be to simply do a GPS lookup and only fall back to last location if it won't work for any reason? And if the app has to fall back to last location just accept it - and give user a clear indication how old it might be (modulo 1024 weeks).

**Comment by forrestguice** [comment]
That is something to consider. ..but it also helps to read the docs in the first place ;) if I had, I would have noticed their stern warning against using [Location.getTime](https://developer.android.com/reference/android/location/Location.html#getTime()). They promise `elapsedRealTimeNanos` is monotonic and a reliable way to calculate location age.

That said, you aren't wrong - for a one time lookup it probably makes sense to use the last location as a fallback, not a starting point, but there is also "current location" mode which hits the provider more frequently. Anyhow the goal was power savings - to keep the app out of the battery list by avoiding repeated lookups.

**Comment by xandro0777** [comment]
One possibility would be to make the manual requests and the first request since boot / upgrade always do a GPS lookup and use that to compare the various times to figure out if some of them would be safe to use for get last location.

**Comment by xandro0777** [comment]
Whatever you have done, the current F-droid version works :)
