### ISSUE TITLE
Chinese mistake in World map dropdown

### ISSUE THREAD

**Issue by qmolee** [forrestguice/SuntimesWidget#380]
Chinese mistake in the dropdown on the world map feature.
items from the top to down in the list are the following.
```
基礎
藍色彈珠
極性
Polar [South]
```

I suggest they could be following
```
預設
衛星
北半球視角
南半球視角
```

**Comment by forrestguice** [comment]
Hi, thanks for reporting. I don't speak any Chinese so I must rely on contributors to review and fix any mistakes. I appreciate it.

The Chinese translation was added in v0.9.4 by @pggdt. The latest version of the app is v0.12.4, so the translation could definitely use an update.

I'll accept a pull request if you'd like to bring the translation up-to-date. The strings are kept in https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/res/values-zh-rTW/strings.xml (with untranslated values marked TODO). A typical workflow is to fork, create a branch, modify the specified file, push your changes, and then finally create the pull request. I can help if any of that is unfamiliar.
