### ISSUE TITLE
NullPointerException: Unable to destroy activity

### ISSUE THREAD

**Issue by anlalalu** [forrestguice/SuntimesWidget#381]
###### Reproduction Steps
This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am start -n com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity2

###### Stack Trace

E/AndroidRuntime(11043): FATAL EXCEPTION: main
E/AndroidRuntime(11043): Process: com.forrestguice.suntimeswidget, PID: 11043
E/AndroidRuntime(11043): java.lang.RuntimeException: Unable to destroy activity {com.forrestguice.suntimeswidget/com.forrestguice.suntimeswidget.SuntimesConfigActivity2}: java.lang.NullPointerException
E/AndroidRuntime(11043): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3483)
E/AndroidRuntime(11043): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3501)
E/AndroidRuntime(11043): 	at android.app.ActivityThread.access$1400(ActivityThread.java:135)
E/AndroidRuntime(11043): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1249)
E/AndroidRuntime(11043): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11043): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(11043): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(11043): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11043): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(11043): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(11043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(11043): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(11043): Caused by: java.lang.NullPointerException
E/AndroidRuntime(11043): 	at com.forrestguice.suntimeswidget.SuntimesConfigActivity0.onDestroy(SuntimesConfigActivity0.java:188)
E/AndroidRuntime(11043): 	at android.app.Activity.performDestroy(Activity.java:5403)
E/AndroidRuntime(11043): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
E/AndroidRuntime(11043): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3470)
E/AndroidRuntime(11043): 	... 11 more

###### Debug info

Android Version = 7.1.0

**Comment by forrestguice** [comment]
Thanks for reporting. What version of Suntimes? v0.12.4 obtained from F-Droid?

This crash looks like one of the bugs fixed in v0.11.9; https://github.com/forrestguice/SuntimesWidget/issues/353

**Comment by anlalalu** [comment]
Yes, it seems to be fixed. Thank you for the reply.
