### ISSUE TITLE
Notification for dismissing an alarm early

### ISSUE THREAD

**Issue by shanemd** [forrestguice/SuntimesWidget#387]
First, thank you for building such a great application! I had dreamed of setting my alarm clock with the sun and had considered writing an app for this myself, then I found Suntimes! I like it so much, I want to help it be even better:

The built-in Android  alarm application presents a notification (silent I believe) roughly an hour before the configured alarm actually goes off. This notification allows you to dismiss the alarm before it goes off, while leaving the recurring alarm enabled. This feature is incredibly helpful in certain circumstances. For instance, when you wake up before your morning alarm clock.

I use SunTimes as my morning alarm clock and frequently get up before my alarm. Occasionally, when I really need my phone to stay quiet, I'll just disable the recurring alarm. But then sometimes I forget to re-enable it, and wake up late the next day... :sad:. I would find this feature incredibly helpful.

**Comment by forrestguice** [comment]
Thanks for bringing this to my attention, I'd overlooked this detail. There really ought to be some way of dismissing a repeating alarm early. I've made a few small changes to accommodate this (a band-aid), but I think more can be done to improve UX (but these changes will have to wait for next minor release).

There was actually a "reminder notification" already but its only shown on older devices (api20-)). I've added a "dismiss" button and changed it so the notification is displayed on all devices (a side-effect is that newer devices will display two alarm icons). I've noticed the button seems to be hidden on some devices - you may need to swipe down on the notification to reveal it.

A caveat.. after an alarm is dismissed early it gets rescheduled (for next cycle), but there isn't any memory of skipping the alarm. If the device reboots (triggering a reschedule on all alarms) these skipped alarms will revert to their previous state (the current cycle), and you'll have to dismiss them again.

**Comment by forrestguice** [comment]
I'll tag v0.12.5 on Friday. It should make it to F-Droid sometime next week.
Please keep an eye on it and let me know if it misbehaves.

**Comment by shanemd** [comment]
Thanks @forrestguice! I'll look for the release of f-droid.

**Comment by Friptick** [comment]
@forrestguice Is this done? It's not closed so it appears still outstanding. Other resolved issues seem to have stayed open too, it's a bit confusing.

**Comment by forrestguice** [comment]
@Friptick Yeah, I'm not great at closing issues. When they are closed, its thanks to automated closing keywords. If an issue has a milestone assigned to it, its generally considered "done" (and can probably be closed or replaced).

It is possible to dismiss and reschedule a repeating alarm early. This is done.
However, its can only be done from the "reminder notification" (displayed up to ~12 hours before), and the alarm list itself doesn't really indicate anything has happened. So there is room for improvement - many people might conclude the feature isn't present.

Anyhow, I'm not too picky about how this tracker is used. I consider it a means of communication above all else, but I'll see about cleaning it up a bit.

**Comment by Friptick** [comment]
OK @forrestguice. Some developers are the exact opposite and close issues without resolving or explaining anything :) But I never blame them, it's their project and they decide. Just remember that you're the boss. :)

**Comment by Friptick** [comment]
Works great! Thanks @forrestguice
