### ISSUE TITLE
Map app? 

### ISSUE THREAD

**Issue by gendernihilist** [forrestguice/SuntimesWidget#391]
There are a few open source map apps on f-droid, I'm wondering if any are recommended as particularly compatible with Suntimes or if any are known to have problems?

**Comment by forrestguice** [comment]
Hi. The map integration is pretty generic - any map app that accepts a "geo intent" should work. I think stock android only comes with one such app (Google Maps), but if an app isn't available then Suntimes should display a message.

I don't know of any major problems with the current map integration, but supposing you encounter any, I'd be interested in your experience.

I personally favor OSMAnd~ for this, however I've noticed it attempts an address lookup before displaying the location, which can be a little annoying. I think its actually possible to improve integration specifically with OSMAnd~ (#372) by using their API (vs a generic intent) but I've held off on doing this.

**Comment by gendernihilist** [comment]
Thank you so much! I'm giving OsmAnd a whirl right now and I love it! Whether you improve integration or not I think I've found a new favourite map app!
