### ISSUE TITLE
Increasing volume for alarms

### ISSUE THREAD

**Issue by efraletti** [forrestguice/SuntimesWidget#396]
Hello, excellent app.

The alarms and notifications are very useful.

I would like to suggest a setting for increasing volume for alarms, as it would greatly improve this functionalities.

Thank you.

**Comment by forrestguice** [comment]
Like a gradual fade-in, so alarms are not so abrupt? Sounds reasonable.

**Comment by efraletti** [comment]
yes, exactly.

I just changed my android to English to check in the default clock app.

It is called gradually increase volume, and it has options for setting this from 5 to 60 seconds in 5s intervals.

This means playing the alarm sound from 0 to 100% volume in 5s, 10s...55s or 60s, per user configuration.

I use 40s and like it very much, it never startles me and don't bother others if it goes off in public or silent environments.
