### ISSUE TITLE
[feature request] Roman timekeeping

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/SuntimesWidget#397]
Hello, how long would it be to add a feature showing the 24 Roman “hours?” – a plus would be the option to set alarms following these Roman hours.

Here’s their definition:
1. Compute sunrise and sundown (done! – in app)
2. Divide both intervals in twelve smaller intervals
3. Number all of these from I to XII, twice.

What you get is exactly how people got track of the day till the latter 1800s – until clocks spread everywhere.

In this system, unlike on clocks, “hours” don’t last 60 min in daytime nor night-time, as shown on this picture:
![1023px-Ancient_Roman_time_keeping_hora_vigilia_equinox_solstice svg](https://user-images.githubusercontent.com/28948599/78693488-9cbd5680-78fb-11ea-946d-79e04f36c4e7.png)
Reference: https://en.wikipedia.org/wiki/Roman_timekeeping

Words and expressions still in use today derive form this system : “the eleventh hour” (= late in the day), “siesta” (nap) = VI-th hour of the day, …

Chronobiology also refers to these Roman hours, with roughly: V-th hour better thinking, VI-th hour best time to have lunch, XI-th hour best physical exercise time, …

Note of interest: I tried showing the mechanism to people with the following HTML+JS page, unfortunately only properly working as a local file (because of geolocation code not working on my own server, due to https not turned on) http://sgalex.free.fr/roman-solar-clock.html
Maybe part of this code might be used?

**Comment by forrestguice** [comment]
These are some neat suggestions. I really appreciate the level of detail. Thank you. I can't promise they will all be implemented but please keep the ideas coming. 

"Roman Time" sounds like a lot of fun. I'm not sure its within scope of the main app though. I struggle to determine where that line is (and the app has grown significantly over time). However I can easily imagine this as an add-on. I've been working on ways to extend the app by providing access to configuration, data, common ui, etc. Here's a recent [example](https://github.com/forrestguice/SolunarPeriods). 

As a separate addon it could explore the idea in greater detail, focus on unique visualizations, features, etc. A few disadvantages; its another apk that must be named ("Roman Time Widget" at this rate), another apk to maintain, and the interfaces mentioned are limited and still being developed (e.g. support for "roman time" alarms may be challenging).

**Comment by forrestguice** [comment]
I've been been exploring this recently. I ended up making https://github.com/forrestguice/NaturalHour, which is pretty basic, but it has some potential I guess.

There's should be a debug build [here](https://github.com/forrestguice/NaturalHour/runs/1158582988) under "artifacts" (courtesy GitHub Actions) if you'd like to try it. Additional suggestions, use cases, or feedback welcome. I will probably tag a first version after playing with it for a few more weeks.

btw, the `res/values/clockface.xml` file defines the appearance; colors, dimensions, etc, which can be changed to produce a completely different watch face. There are too many possibilities here and I'm not really sure I want to get into designing clock faces.. :\

**Comment by XanderLeaDaren** [comment]
That’s great! I just got this build onto my phone, it’s working here, too. 

The option to choose which usual common hours to display on the inside circle is a neat addition, and 12 on top is imho the best practice, following the Sun path.

I’ll check the time with it in the days ahead. Today, the only “eagerness” I have is to display it as a widget! 😄

**Comment by forrestguice** [comment]
The [latest](https://github.com/forrestguice/NaturalHour/runs/1203853899) adds a widget - its intentionally simple (no individual widget config, it mirrors the app).

I like 12 on top too (seems most intuitive). Apparently people are pretty picky about these things, so I've exposed an option to choose top or bottom (along with a bunch of other flags that were previously hidden). The starting position is actual defined as an angle, so its equally possible to draw the clock on its side, or something else weird. Twilight periods have been added. I think the colors (or lack thereof) leave a lot to be desired. That's next I guess.

I've read in various sources about competing definitions of "day", and debate over whether the day was bounded by sunrise/sunset, or instead by dusk. I wanted to explore that, so I've added an option to define the day as starting/ending with civil twilight. So far this alternate definition actually seems pretty intuitive to me (although less exact).

**Comment by XanderLeaDaren** [comment]
Hey there, you did an amazing job adding all of these flags options! Congrats!
I especially love the grey areas related to twilights… and – geekly enough – also the vigilæ. :wink:

I’m putting the widget on my home screen and I’ll be letting you know about it after some days.

Thanks a lot for this, and for the Earth-projection Sun position widget from Suntimes. Both are really good tools. 👌🏽

**Comment by forrestguice** [comment]
btw, I'll tag a first release this weekend. I've actually been meaning to do that for a couple weeks now, but never seem to get around to it. 

My intention was to polish up a few things, but progress has really slowed (time spent elsewhere). Even with the rough edges, I think this is probably a good stopping point (v0.1.0).
