### ISSUE TITLE
[feature request] Solar Hijiri Calendar

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/SuntimesWidget#398]
Hello, how feasible would it be to add a widget showing the date according to Solar Hijiri Calendar?

Here’s the definition:
1. First day of the year is after midnight between the two consecutive solar noons, which include the instant of the March equinox.
2. The first six months have 31 days. Their names are: Farvardin, Ordibehesht, Khordad, Tir, Mordad, Shahrivar
3. The last five months have 30 days. Their names are: Mehr, Aban, Azar, Dey, Bahman
4. The very last month (named Esfand) actually might be 29 days / 30 days, depending on leap years. No need to know when is a leap year, because the new year depends on March equinox!

Interestingly enough, these months correspond to zodiac signs, hence equinoxes and solstices occur on the 1st day of every third month. And thus, adding this feature is also a mean to display astrological signs!

Some reference: https://en.wikipedia.org/wiki/Solar_Hijri_calendar

**Comment by islam2hamy** [comment]
That is totaly not true

**Comment by XanderLeaDaren** [comment]
Hi,

From your location (Egypt) İ would think you’re comparing my definition of the _Solar_ Hijiri Calendar (used in İran and Afghanistan, based on the Jalali calendar by Omar Khayyam & al.) with the usual (_lunar_) Hijiri Calendar used in other countries, thus your assumption it being “totally not true”.

**Comment by islam2hamy** [comment]
Hi ,
What is your religion ?

**Comment by XanderLeaDaren** [comment]
Hello again.
İf İ may: no offense, but my being Sunni, Shia, or from any other religion belief has nothing to do with scientific calculations needed here as part of this programming project aiming to provide a calendar date.
