### ISSUE TITLE
[feature request] Alarm clock: set an alarm for a moment defined in solar time

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/SuntimesWidget#403]
Hello,

I’m wondering on how much work would be needed to add the ability to set an alarm at a specific time, with {hours:minutes} entered in mean/apparent solar time.

I know Suntimes already has access to solar/apparent time, since the 3×1 Clock Widget has the option to display them. So in my mind, it would just be necessary to add two options in the New alarm/notification drop-down list: “mean solar time” and “apparent solar time”, then set the desired time with the usual built-in Android handclock face window.

**Comment by forrestguice** [comment]
I think this can be included in next patch (v0.12.8).

It is currently possible to select "Override Time" and choose a "clock time" (uses the system time zone), turning Suntimes Alarms into an ordinary alarm clock. I think a drop-down could be added here to allow for solar time.

The UI itself leaves a lot to be desired (feature is basically hidden). I'm hoping to come up with something better for v0.13.0 that improves discoverability.
