### ISSUE TITLE
Sort alarms and notifications

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/SuntimesWidget#413]
Hi there,
and thank you for the good work in last releases (especially solar time -defined alarms!😉)

I was wondering how alarms and notifications are sorted and it seems to me the last entered one is on top, going down to the first entered one, in last position on the list. Correct?

I didn’t find any way to sort them, either manually nor by any logical way – either by tapping, dragging, long-tapping, …

I figured it may be more convenient to have all alerts (alarms+notifications) sorted by triggering time – or to allow the user to choose to sort them this way, if not by default. As a bonus, the first entry on the alert list could be the next one that is about to trigger. I understand this bonus part means reordering depending on the time you check the list, but what do you think?

**Example**
Now:
* Alarm 9:42 AM
* Notification 6:15 AM
* Alarm 7:23 PM

would become this sorted list:
* Notification 6:15 AM
* Alarm 9:42 AM
* Alarm 7:23 PM

and (the bonus part) if it’s, let’s say, 4PM when I’m checking the list:
* Alarm 7:23 PM
* Notification 6:15 AM
* Alarm 9:42 AM

**Comment by forrestguice** [comment]
> it seems to me the last entered one is on top

That's correct. The list isn't really sorted at the moment. The current order is just rowid (descending).

I think allowing for different sort options makes sense, especially as proposed. A "sort by" submenu could be added to the action bar with a couple choices.

Sort by:
* Alarm Time:  As proposed, next alarm first, and the new default.
* Creation Date:  As currently ordered, last alarm created first.

I think manual reordering by dragging, while really neat, is a lot more difficult (and won't be implemented any time soon). This is something to try for eventually though.
