### ISSUE TITLE
Cant install through F-Droid

### ISSUE THREAD

**Issue by enomado** [forrestguice/SuntimesWidget#418]
![image](https://user-images.githubusercontent.com/707007/82839176-2c808980-9ed7-11ea-95a6-d931fd5598c2.png)

But can download newer version manually https://f-droid.org/repo/com.forrestguice.suntimeswidget_61.apk

**Comment by JonnyTech** [comment]
This should be reported to the F-Droid team as they build and host the APK's.

**Comment by forrestguice** [comment]
Its an issue with the F-Droid client not refreshing the list of available apks. Unfortunately I don't really have any details. You can try pulling to refresh but might not work..

F-Droid only keeps the last 3 or 4 versions before moving them to the archive. The most recent Suntimes release was v0.12.10, so by now v0.12.5 is no longer available (and you get that error message).
