### ISSUE TITLE
[Feature] Delete individual places

### ISSUE THREAD

**Issue by SebiderSushi** [forrestguice/SuntimesWidget#419]
Short of clearing the whole list and recreating all entries, is there a way to remove individual user defined places?

**Comment by forrestguice** [comment]
Unfortunately no, but this feature can be added to the next minor release (v0.13.0). 

The current design is only to "remember" previous entries (so as to be easily reselected), but I think it makes sense to add a "manage places" screen that displays a complete list and allows add/edit/delete.

**Comment by SebiderSushi** [comment]
This would be awsome. Over time, my list grew a bit with places that are no longer relevent but at the same tine there's a lot of places i surely want to keep.


On another note: There's an export feature but no import feature for the places, right?
Since i'm rooted i don't care all that much as i always back up and restore all of suntimes data, but

**Comment by forrestguice** [comment]
Import places is still on the TODO list.
If we can dump the list (to cvs) its easy enough to import (from csv), but I'm kind of wary of potential user expectations. There are so many formats for storing locations, next thing I know I'll be trying to support those formats. That said, it might be worthwhile to pick just one and support it; GeoJSON maybe? I dunno.

**Comment by moebius1** [comment]
Bonjour,
Thank you for this very pleasant program.
I also agree with SebiderSushi : an import process for the previously exported places would be great especially when you need to change the phone. It's a little boring to copy every coordinate (I have a lot of them :-) )
Anyway it's a great program, very nice, thank you for bringing it to us.
cordialement,
