### ISSUE TITLE
sun position bar widget does not render midnight sun

### ISSUE THREAD

**Issue by eskerda** [forrestguice/SuntimesWidget#421]
Steps to reproduce: set lat/lng to 69.6492° N, 18.9553° E

what was expected: something like

![Screenshot_20200614_182631](https://user-images.githubusercontent.com/208952/84598660-a075d800-ae6c-11ea-8567-4d1830098215.jpg)

what it shows:
![Screenshot_20200614_182734](https://user-images.githubusercontent.com/208952/84598673-bf746a00-ae6c-11ea-8b42-7c0e7ced7822.jpg)

**Comment by forrestguice** [comment]
Thanks for reporting this problem. I just gave it a try and can confirm its crashing after adding the widget, then falls back to displaying the 1x1 widget. It will be fixed in v0.12.12.

**Comment by eskerda** [comment]
@forrestguice thanks a lot for taking a look at this! I thought it was a very fun bug.
