### ISSUE TITLE
Widget width and layout tweaks

### ISSUE THREAD

**Issue by JonnyTech** [forrestguice/SuntimesWidget#423]
These are cosmetic requests so very low priority:

Text is cropped on my widget, is it possible to increase the widget width to accommodate?

![img_2](https://user-images.githubusercontent.com/3584732/87299543-233d9180-c504-11ea-9557-85bfe81d43fa.jpg)

And maybe space out the icons above to be both left and right justified?

Would be nice to have either both icons or both times together to be symmetrical.

**Comment by forrestguice** [comment]
Apologies for taking so long to get to this. Its been awhile since I've looked at these layouts - what I remember is its a struggle to make things look consistent. 

I've played with the layout a bit more. This next release might be better. The sunrise/sunset times should now centered, but the cropping problem confuses me. 

The layout should wrap_content and expand as needed to consume available space (and only crop after taking up the entire cell). I'm assuming the widget dimensions in the screenshot are far left/right (looks like 4 or 5 cells), and not at the widget frame (2 or 3 cells). A screenshot that includes the bounding rectangle might help me understand. Your screen dimensions and dpi should help reproduce this in the emulator.

**Comment by forrestguice** [comment]
It looks like the inner widget frame is match_parent, but the outer frame was wrap_content. hrm. That seems like an error; both should be wrap_content.

At any rate, please post another screenshot with v0.13.0 when it eventually lands in F-Droid (next week or two), and we can try at fixing this again.

**Comment by JonnyTech** [comment]
Looks like the issue may be with my launcher.

Here are screengrabs from stock quickstep launcher - when adding the widget then the third one is automatically applied:

![Screenshot_20200910-111238-nq8](https://user-images.githubusercontent.com/3584732/92983129-94181000-f499-11ea-9422-f4a82e7e0f60.png)
![Screenshot_20200910-111247-nq8](https://user-images.githubusercontent.com/3584732/92983090-6e8b0680-f499-11ea-9b94-4a2c4806b338.png)
![Screenshot_20200910-111255-nq8](https://user-images.githubusercontent.com/3584732/92983091-6f239d00-f499-11ea-8c56-7780994a6b20.png)
![Screenshot_20200910-111301-nq8](https://user-images.githubusercontent.com/3584732/92983092-6f239d00-f499-11ea-809e-833b647f831a.png)
![Screenshot_20200910-111309-nq8](https://user-images.githubusercontent.com/3584732/92983093-6fbc3380-f499-11ea-8d18-fe88a6b4492b.png)

But I was originally using OpenLauncher which automatically applied the second size (excuse the lack of bounding boxes):

![Screenshot_20200910-122930-nq8](https://user-images.githubusercontent.com/3584732/92983199-dc373280-f499-11ea-9540-5afc16fffcf5.png)
![Screenshot_20200910-123023-nq8](https://user-images.githubusercontent.com/3584732/92983200-dccfc900-f499-11ea-8891-3a236a2d33a8.png)
![Screenshot_20200910-123037-nq8](https://user-images.githubusercontent.com/3584732/92983201-dd685f80-f499-11ea-91d5-bb4093b043cf.png)
![Screenshot_20200910-123055-nq8](https://user-images.githubusercontent.com/3584732/92983203-dd685f80-f499-11ea-920f-8e97ac7c99f1.png)
![Screenshot_20200910-123123-nq8](https://user-images.githubusercontent.com/3584732/92983204-de00f600-f499-11ea-9096-5cd14bdc278a.png)

Thanks for the update though, I shall report back after it drops in F-Droid.

**Comment by JonnyTech** [comment]
Sorry for reopening an old thread (and my lack of original reply).

Just looking at this again to get a good layout for the widget (I added the solar noon info too). The bottom line of text is either cropped or not centered.

Suntimes: 0.14.10
Android: AOSP 11
Font size: Default
Launcher: Trebuchet (stock)
Widget: 2x1 Sunrise & Sunset

![1](https://user-images.githubusercontent.com/3584732/202763281-a599a5c0-5bf5-481c-96f1-fbdf61f7426a.png)
![2](https://user-images.githubusercontent.com/3584732/202763300-263bfe2b-9019-4d26-af60-90dbd65174fc.png)
![3](https://user-images.githubusercontent.com/3584732/202763390-982d65ee-a421-4992-9681-e2fc1e9b205c.png)

Is it possible to center everything (both horizontally and vertically), including the text at the bottom? Having the whole layout symmetrical would make it so much more pleasing to the eye.

If you're up to a challenge, maybe place the icons as sunrise, solar noon, sunset, on a single line, therefore showing the information chronologically.

I looked at `/app/src/main/res/layout/layout_widget_2x1_*.xml` but could not find the relative entries - to be honest, I have no idea what I am looking for!

**Comment by forrestguice** [comment]
I'll take another look at this. 
What are your alignment options set to? The screenshots looks like `fill entire cell` is checked (but its hard to say).

> I looked at /app/src/main/res/layout/layout_widget_2x1_*.xml but could not find the relative entries - to be honest, I have no idea what I am looking for!

There is a lot of duplication (thanks to severe limitations of `RemoteView`). It gets confusing pretty quick.

*  `layout_widget_2x1_0_*` are the "rising" layouts (order is sunrise, sunset). They are all wrappers around `layout_widget_2x1_0_content`.
* `layout_widget_2x1_01_*` are the "setting" layouts (order is sunset,sunrise). These are all wrappers around `layout_widget_2x1_01_content`. 
* `*_align_fill` are the "fill layouts", while `*_align_float_*` are alignments (1 is top-left, 9 bottom-right). 

All of these (other than `_content`) are basically wrappers (and could be conceivably auto-generated).

**Comment by JonnyTech** [comment]
Yes, you are correct, I did check `Fill entire cell`.

![IMG_20221119_084857](https://user-images.githubusercontent.com/3584732/202843019-b789b1bd-b0aa-4430-b948-58e62b2232c6.jpg)

It looks much more difficult than I thought!

**Comment by forrestguice** [comment]
> Is it possible to center everything (both horizontally and vertically), including the text at the bottom? Having the whole layout symmetrical would make it so much more pleasing to the eye.

I've made a few tweaks in `v0.14.11` - text at the bottom is now centered horizontally, and the "fill" layout is now centered vertically (except for title which remains upper left).

> If you're up to a challenge, maybe place the icons as sunrise, solar noon, sunset, on a single line, therefore showing the information chronologically.

This is now on the list for `v0.15.0`; there's some working code in this [branch](https://github.com/forrestguice/SuntimesWidget/tree/widget-sunposition1x3).

> It looks much more difficult than I thought!

Its a drag, but if you don't mind additional resource duplication, its doable for individual layouts. It discourages me from adding more options though. e.g. making alignment configurable within the fill layout implies another 18 files. Pretty silly.. but RemoteViews doesn't expose the methods we need to change the layout_params programatically.

**Comment by JonnyTech** [comment]
Thank you, new release is improved :)
![2w](https://user-images.githubusercontent.com/3584732/205469674-647b6dce-b5fe-491a-9b71-9384218a3111.png)
![3w](https://user-images.githubusercontent.com/3584732/205469679-4a420933-73f7-451d-9081-67dc96a52887.png)
![4w](https://user-images.githubusercontent.com/3584732/205469683-6ae54847-8c9a-49c8-a45b-bc9a4851c2b8.png)
