### ISSUE TITLE
Alarms: show actual time

### ISSUE THREAD

**Issue by jtagcat** [forrestguice/SuntimesWidget#424]
Right now it's 'n hours after x', would be nice to see n+x displayed.

**Comment by forrestguice** [comment]
This would be useful. Perhaps tapping this label could cause it to animate between n+x and back again. It'll be included in the next release.

**Comment by jtagcat** [comment]
> This would be useful. Perhaps tapping this label could cause it to animate between n+x and back again. It'll be included in the next release.

IMO there's room for the time to be displayed without tapping.

Natural expectation would be editing, when tapping on the time, and most people might not notice that.

**Comment by forrestguice** [comment]
This detail and a bunch of others have been changed in v0.13.0. The actual time is now displayed for all non-focused items, but once focused switches to the n+x format. Also, editing alarms has been moved into its own activity where the n+x format is displayed by default (but momentarily animates/transitions to the actual time whenever those options are changed). It requires more clicks to navigate the UI, but there is a lot more room in general. I no longer feel like these features are being hidden. 

It should land in F-Droid in the next week. Feedback welcome.
