### ISSUE TITLE
Clarify "Actual Time" in the Help

### ISSUE THREAD

**Issue by ericjs** [forrestguice/SuntimesWidget#432]
Since the sun is not a point source, "on the horizon" is not clear enough. Touching the horizon at the bottom? Bisected by the horizon? It also would be nice to define "horizon". I assume you must mean "standard sea level".

**Comment by forrestguice** [comment]
Well, technically sunrise is "the moment at which the upper limb of the Sun appears tangent to the horizon", but I'm not sure there is actually any value pointing that out. The help is intentionally brief and I'd rather not fill it with standard definitions.

**Comment by forrestguice** [comment]
Perhaps just adding the phrase "upper limb" is enough to clarify things without complicating the definition.
"Actual Time: `the upper limb of` the sun is on to the horizon. This is the approximate time of sunrise and sunset."

**Comment by forrestguice** [comment]
This is a nice article; https://www.nationalgeographic.org/encyclopedia/horizon/

Again, to get technical with it, "horizon" refers to the "geographic horizon" and not necessarily "sea level horizon" (unless actually at sea level), and definitely not the "local horizon".

**Comment by ericjs** [comment]
I think "upper limb" isn't going to be very clear to a layman.

Looking at the pages you linked, it's still a little unclear to me what "geographic horizon" is. It's not clear to me if both "geographic horizon" and "sea-level horizon" both use what the horizon would be like if the surrounding topography were flat and at sea-level, and differ only in taking viewer altitude into account or not, or if "geographic horizon" uses some other way of ignoring "local prominences". Given natural irregularity of surface elevation variation I don't know how you draw a clear line between what is topographic prominence to be ignored and local elevation above sea-level to be counted.

**Comment by forrestguice** [comment]
I was kind of thinking the same, "what's an "upper limb".. This is why I think less is more.. Its better not to confuse people. I guess a simple way of putting it is.. sunrise is the moment the top of the sun becomes visible above the horizon, and sunset the moment the top of the sun disappears below it.

> Given natural irregularity of surface elevation variation I don't know how you draw a clear line between what is topographic prominence to be ignored and local elevation above sea-level to be counted.

Your understanding of geographic horizon sounds fine to me. Local prominence is ignored. We have no knowledge of that. What we have instead  are different models of the curvature of the earth (not a perfect sphere), and an adjustment for altitude above it. This is literally the only difference between the time4a-cc and time4a-4j calculators.

**Comment by ericjs** [comment]
> sunrise is the moment the top of the sun becomes visible above the horizon, and sunset the moment the top of the sun disappears below it.

I think that wording is clear and understandable by any layman.

**Comment by forrestguice** [comment]
Another wrinkle - the twilight events are measured from the center. Only sunrise/sunset uses the upper limb. 

In the last patch I removed the details. I think what is essential is knowing that "Actual Time" is a synonymous for sunrise/sunset (as it appears in the UI). I was considering reversing that and putting a technical definition there (like "the upper limb of the sun is on the geographic horizon"), but I also think the in-app help needs to be as concise as possible (one or two sentences per topic max).

So maybe instead the help dialog should link to some online resource. I think the project wiki could be used to host online help. That would also allow others to contribute (since this sounds like a ton of work).
