### ISSUE TITLE
Incorrect indicated Future and Past number of days, when DST starts or ends

### ISSUE THREAD

**Issue by rodri** [forrestguice/SuntimesWidget#436]
In Suntimes 0.13.1, being today 2020-10-21, when I scroll to future days, it shows Future (+3) for 2020-10-24 and then, Future (+5) for 2020-10-25, instead of Future (+4). The calculation of the number of days to the future and to the past seems to be off-by-one when there is a Daylight Savings Time change in that day. In my place DST ends at 2020-10-25. Also tried scrolling to the past to the last DST change, and a similar issue appeared, to the inverse instead.

**Comment by forrestguice** [comment]
Thanks for reporting this. I'll take a closer look in the next day or so and get this fixed.
