### ISSUE TITLE
[RFE] Widget: Reduce margin

### ISSUE THREAD

**Issue by genodeftest** [forrestguice/SuntimesWidget#445]
The suntimes widget is currently very small: It does not fill the screen space it is given by the launcher. You can see the space it is given by resizing the widget which will show a border around the widget.

Suntimes:
![Screenshot_20200912-025252](https://user-images.githubusercontent.com/934401/98439624-65ae5e00-20f3-11eb-9234-185b03860855.png)

For comparison [Simple Clock](https://github.com/SimpleMobileTools/Simple-Clock):
![Screenshot_20200912-025306](https://user-images.githubusercontent.com/934401/98439653-91314880-20f3-11eb-880d-88037351ad3a.png)
This app completely fills the given resize border and thus the available screen space.

Would it be possible to make the widget use more of its available space? This way, the icons and font could be larger (or one could have more info on the widget).

Additional info:
* Suntimes 0.13.2 from f-droid store
* stock Android 9 patchlevel 2020-10-01

**Comment by forrestguice** [comment]
I think this is doable, w/ a few caveats.

Unfortunately I don't think its actually possible to squeeze more information in the provided space. The extra space disappears completely on smaller screens, and the widget dimensions aren't consistent from one device to another. So for example, if we want a third column, it'll need to be designed as a larger widget (requiring an additional cell).

However, consuming that extra available should be possible. For example, check out the 3x1 clock widget - the text should expand similar to your second screenshot. I think that same kind of effect is doable w/ the other widgets.

I'm not sure its possible to apply this effect to the existing widget layouts without redesigning them. The clock widget basically scales the text until the layout breaks (then steps back a size). I think ideally this could be added as another option to be checked/unchecked, but more realistically I think it will probably end up being its own widget(s).

btw, A workaround is to fiddle w/ the theme and set a larger (static) font size. This isn't nearly the same, I know,

**Comment by genodeftest** [comment]
> However, consuming that extra available should be possible. For example, check out the 3x1 clock widget - the text should expand similar to your second screenshot. I think that same kind of effect is doable w/ the other widgets.

This is what I mean. Having more content here may or may not be of interest, but having it more readable due to larger size would be perfect.
