### ISSUE TITLE
Inconsistent colons in the options

### ISSUE THREAD

**Issue by HerHde** [forrestguice/SuntimesWidget#45]
Ahoi,
some option names end with a `:`, some not. I guess this is due the appearance in the widget config, where the names are in the same line as the values.
Could you append the colons to the strings within the widget config, so there are no colons within the translations etc?

Greetings
~HerHde

**Comment by forrestguice** [comment]
I am not sure I follow - can you show me a screenshot with an example?

Those strings should be in the context of a label (I just double checked them, they shouldn't appear alone without a value) so I think it should be left up to translator if they have colons or not. I do notice that some labels come after the value (checkbox for example) and in this case there is no ":" .. is this what you mean? btw, the layouts are translatable too, so if convention dictates a different order we can fix that.

I would prefer not to go appending things to the strings in code - it would be better if we could fix inconsistencies without locale specific special handling.
