### ISSUE TITLE
Alarm reenable

### ISSUE THREAD

**Issue by petesimonic** [forrestguice/SuntimesWidget#455]
Hello! User can't find a way to reenable the alarm. How does he open the screen with disabled alarm?

The only way found so far is creating a new alarm, then enabling the needed one, and deleting temporary that let open alarms screen.

**Comment by forrestguice** [comment]
Sorry but I'm not sure I understand. It sounds like a bug, but it would help if you would list the steps you are taking, what you expect to see after each step, versus what you actually see.

To edit an existing alarm you just need to tap it twice (first time to select it, second time to open the edit screen). Also, to reenable an existing alarm, you can just tap the slider (upper right corner). Are these not working correctly?

**Comment by petesimonic** [comment]
Indeed! We're just stupid enough not to find *how to open the *alarms screen**. Basically user just open the app (main screen) and can't find a way to alarms to enable his beloved sunrise alarm (men, it's awesome!). So he ought to create a new alarm to get to the screen, then delete this new temporary alarm, then :tada: he enables good ol' alarm he loves to use regularly.

Of course we're looking for a straightforward path: open alarms, enable the alarm. But UI turned out to be too confusing (for me and retarded friends). =)

P.s. Strange things. I'm sure I answered you yesterday... Thank you for swift reply which made me to check if the answer showed up.

**Comment by forrestguice** [comment]
Thanks for the clarification. I understand now. I think of this as a UX issue - nothing is broken but we can do better.

I'm thinking this can be improved by adding an edit button (looks like pencil) immediately left of the delete icon. So tapping the alarm once would reveal those icons, and either tapping the alarm again OR the edit button would open the edit screen. This would provide some clue the functionality is there, and eventually users will figure out that tapping twice does the same thing.

**Comment by petesimonic** [comment]
No-o-o! =)) Alarms screen is clear as light.

I'm sorry, I'm not a native speaker... You were talking about screenshots. Let's try.

The question is: how does user get from the left screen to the right *without creating a new alarm?* (Assume that the only created alarm is disabled.)
![image](https://user-images.githubusercontent.com/69221333/100522589-5040c700-31bb-11eb-8fab-fdac2c7c94b7.png)

P.s. I believe it could be done. But that could be more verbose so all users could figure it out. So you're totally right: nothing is broken, just confusing a bit.

**Comment by forrestguice** [comment]
Oh.. I see what you mean. Yeah, there is no direct way from the main activity. But look in your app launcher - there should be a "Suntimes Alarms" icon there, appearing as a separate app.

**Comment by forrestguice** [comment]
Another button might be added to the lower left corner of the "Set Alarm" dialog, leading to the list of alarms. Its something I've experimented with before, but I thought it looked a little cluttered. I agree though there should be a way to navigate there quickly from the dialog that creates the alarms.

**Comment by petesimonic** [comment]
There are plenty of options. A link in the very bottom, an icon in-between big time and the current time zone, another button in the row of location and position update. 

Thanks for clarification, it was unexpected move. )) No workarounds anymore. )

On November 28, 2020 11:02:43 PM GMT+03:00, Forrest Guice <notifications@github.com> wrote:
>Another button might be added to the lower left corner of the "Set
>Alarm" dialog, leading to the list of alarms. Its something I've
>experimented with before, but I thought it looked a little cluttered. I
>agree though there should be a way to navigate there quickly from the
>dialog that creates the alarms.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/forrestguice/SuntimesWidget/issues/455#issuecomment-735284014

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
