### ISSUE TITLE
Sideral time

### ISSUE THREAD

**Issue by Knusper** [forrestguice/SuntimesWidget#463]
Professional astronomer here (I work at Cerro Paranal) - I use this app a lot.
One thing that would be nice to have in my pocket would also be the current sideral time.

**Comment by forrestguice** [comment]
I'm glad this app proves useful. :)

I decided to check how feasible this was, and before I knew it had something implemented. It can included in the next patch release.

I've added "local sidereal" (lmst) and "greenwich sidereal" (gmst) to the "solar time" drop-down (which now needs to be renamed; maybe "Time Standards"?). Its now possible to configure the widgets or app to use these "time zones" (another misnomer). 

I'm also thinking the sidereal time could be displayed by one of the dialogs (maybe the solstice dialog, similar to the way the "world clock" dialog displays UTC). I'm not sure where its display would be most useful. I'm not an astronomer - writing code is my way of exploring these topics - my field of study was computer science.

btw, I'm looking at pictures of Cerro Paranal and the view looks fantastic.
