### ISSUE TITLE
Display the remaining light time

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#466]
Hi!

Could we also have the remaining light time displayed, please?

![](https://user-images.githubusercontent.com/982338/103653431-49883b00-4f43-11eb-914a-3def16c8ffa3.png)

**Comment by forrestguice** [comment]
Click on the "Sunrise" or "Sunset" headers - it should cause the "note" area in the upper right corner to jump to sunrise/sunset. The time displayed there is the same thing?

I've been thinking the highlighted area could be extended to show difference in daylight, a message like "1m 30s longer", similar to the widget. Its currently displayed by the "sun position" dialog but only for the current day. If part of the card it would be possible to flip forward/back to see changes over time.

**Comment by naoliv** [comment]
Sorry that I forgot about this.
Yep, clicking on the icons does the job :-)
Thanks!
