### ISSUE TITLE
String not being translated with a forced language

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#467]
It seems that even if I force Suntimes to English, this string is still displayed in Portuguese (my system language):

![](https://user-images.githubusercontent.com/982338/103653729-b4d20d00-4f43-11eb-8bb0-d1050eb98b3f.png)

"Última Posição" = "Last Position"

**Comment by forrestguice** [comment]
hrm, I think this is a side-effect of the funny way its implemented. The label is assigned when the location is retrieved (which is also when its localized), and then retained after the locale switch.
