### ISSUE TITLE
option to select start screen of the app

### ISSUE THREAD

**Issue by JFMugen** [forrestguice/SuntimesWidget#505]
I don't like having 2 icons for the app (main and the alarms) but I only use the app for the alarms. So, choosing which page to see when you boot up would be useful I think. 

Great app btw, thanks :)

**Comment by forrestguice** [comment]
Thanks for the feedback. Its a use case I'd hadn't really considered.

The current option for hiding the Alarm icon works by toggling `enabled` on an `activity-alias` - maybe this can be extended to the main icon too. It might be an easy way to implement this. I'll have to investigate.
