### ISSUE TITLE
1 x 1 Moon Widget uses imperial units while the app metric

### ISSUE THREAD

**Issue by doloresanto** [forrestguice/SuntimesWidget#506]
The app has the Units of Length set to Metric:
![Screenshot_20210905-181337](https://user-images.githubusercontent.com/36057082/132133922-92410d65-8010-4627-b2b3-80925ef46e6b.png)

The units are used in the app:
![Screenshot_20210905-181328](https://user-images.githubusercontent.com/36057082/132133932-6fc983b1-6294-45da-bf94-0626a03bd353.png)

The 1 x 1 Moon Widget with Next Perigee / Apogee shows information in miles instead of kilometers.
![Screenshot_20210905-181308](https://user-images.githubusercontent.com/36057082/132133937-da5d22fd-1dee-4770-8da0-62791b856d70.png)

Same with the Moon Distance widget.

**Comment by forrestguice** [comment]
Thanks for reporting this. It will be fixed in the next patch.

**Comment by doloresanto** [comment]
Thanks!
