### ISSUE TITLE
set alarm depending on a calculation

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#516]
Hi @forrestguice ,
How are you?

Can you help me to do this calculation to set alarm  / notification ?

1.I need to get the hours between actual sunset for today and the astronomical sunrise for the next day

2. Ability to take this number and division  it on 2 or 3 , to use it as alarm  / notification , or addition  it with other event (ex: actual sunset ) to make alarm  / notification
 
Thank you

**Comment by forrestguice** [comment]
Hi @islam2hamy. I'm doing well. 
I don't too much time, but I should be able to help with this over the next couple weeks. 

My initial reaction is this feature is out-of-scope for the main app. However, it can be done as an addon, with the caveat that the alarms/notifications are "one time" (non-repeating alarms), which may limit its usefulness. Repeating alarms based on a calculation would have to be an advanced feature, maybe developed later (the architecture needed to support this is missing).

I put together a layout file while thinking about this. It might looks something like..


![Screenshot_2021-11-07-13-34-11](https://user-images.githubusercontent.com/10246147/140661132-3b69103f-378b-40ea-8c7e-c05855841879.png)

**Comment by islam2hamy** [comment]
Thank you for your attention .

Good initial , that is exactly what i need , so i can set alarm/notification on "1:27 AM" as it is , or after/before "5/10 minutes" as example .

Hope this will be repeatable also , so it will be useful.

Take your time , do your best.

**Comment by forrestguice** [comment]
I've made more progress on this than anticipated. The missing alarm architecture has been added to https://github.com/forrestguice/SuntimesWidget/tree/alarm-addon. The implementation is basically as imagined in https://github.com/forrestguice/NaturalHour/issues/7 (now a year ago, wow time flies..). This should allow addons to declare their own (very arbitrary) repeating alarm events. Next, I'll be extending NaturalHour to schedule alarms for the "roman hours".

The layout mentioned earlier is now a working app; https://github.com/forrestguice/IntervalMidpoints .. it's able to schedule repeating alarms for the midpoints (no caveats).

This came together pretty quickly - I think some "settling time" is required, to discover and fix any bugs.
The plan is to include the new functionality as `v0.14.0` at the start of January.

**Comment by islam2hamy** [comment]
Glad to hear that :)

**Comment by islam2hamy** [comment]
Hi @forrestguice ,
How are you?

Any update about that?

**Comment by forrestguice** [comment]
The last change/fix made to this feature was a few weeks ago. In the meantime I've been working on other stuff. 
I'm running a few weeks behind my own schedule for sure - it was my intention to have the next version tagged by now.

I'll be merging and testing the various feature branches this week, with the release before February.
