### ISSUE TITLE
[feature request] make "sun position" scrollable like the "world map"

### ISSUE THREAD

**Issue by iperfectmail** [forrestguice/SuntimesWidget#519]
Hi there, thanks for the great app!
In the "world map" (I am referring to the menu item) there is this option to fast forward / rewind the position of the sun and the moon by 15 min or 1 day.
I would be interested in this option as well for the "sun position" (the menu item) to check the altitude of the sun at a certain date and time.
At the moment, the only work-around I found was to change the system date and time.
Thanks in advance!

**Comment by forrestguice** [comment]
Thanks, this is an interesting suggestion. I'll consider this.
I can see how a play/rewind/forward type UI would be very useful for that. It seems changing the system time is currently the only way to get the altitude at a specific moment.

I'm thinking that altitude at noon (along with azimuth at sunrise/sunset) should be displayed as part of the main card too, that way it would be possible to see daily changes by flipping forward/back.
