### ISSUE TITLE
Invert moon images/icons for negative latitude values

### ISSUE THREAD

**Issue by jumase** [forrestguice/SuntimesWidget#526]
Hi, first of all, my congratulations for the app!

I'm using version 0.13.16 on Android 10.

Could it be possible to invert the image/icon displayed for moon phases when location is set within places from the south hemisphere? As you may know, the moon is seen differently from north than the way it's seen from south. Particularly it's just the other way round (except for full and new moon of course) so it may be simple to implement, or at least I hope so.

I think there's no need to expand the description nor to upload any screenshot, unless it's something related to my device. Unfortunately, I couldn't check this issue on other devices. In that case, just let me know.

Regards

**Comment by forrestguice** [comment]
Hi. Thanks for the suggestion. It sounds reasonable to me, especially given that the app already makes other adjustments based on hemisphere (flips seasons, etc). 

We can probably flip those first/third quarter and waxing/waning icons as appropriate. It should be easy to implement, but sometimes the details are really ugly. I'll need to investigate first.

**Comment by jumase** [comment]
I'm glad to hear that (except for the ugly details, but well, I wish you good luck). Thank you. I appreciate the way the app is done, as well as the app itself :)
