### ISSUE TITLE
Times are not right

### ISSUE THREAD

**Issue by bcu8heq2** [forrestguice/SuntimesWidget#53]
All times are very wrong as sunrises are shown during the middle of the day for example. It seems that somehow it doesn't get the right time from the system.

**Comment by forrestguice** [comment]
not enough information provided to reproduce

**Comment by forrestguice** [comment]
@bcu8heq2 *bump* hey did you ever figure this out? Can you please post a screenshot here if you're still experiencing the issue.

**Comment by forrestguice** [comment]
so I'm going to go ahead and close this issue.. 

I'm going to chalk this up to confusion over time zones, or some other configuration issue. It seems like a common source of problems and would account for "all times are very wrong", as well as an inaccurate wall clock displayed by the app. I don't think it helps that the default location (whatever that happens to be set to) pretty much always mismatches the default (system) timezone - the whole thing basically starts off misconfigured, so you'll have to either adjust the location, or timezone, or both before it works right.

if that doesn't sound right go ahead and open another issue - but I really need screen shots and a nice (verbose) description of what is happening to be able to reproduce and fix.
