### ISSUE TITLE
Feature Request: Custom Offset +- to Sunset

### ISSUE THREAD

**Issue by codeandfix** [forrestguice/SuntimesWidget#537]
Actually i can see the Sunset Time according to Place+Civil/Nautical/Astronomical.
But i prefer to have an Offset like +1.5h after sunset and -1.5h before sunset based on civil time.

**Comment by forrestguice** [comment]
Hi. If I'm understanding correctly, the feature you're describing is available in SuntimesAlarms.

Try creating an alarm for either `sunset` or `evening civil twilight`, then, from the edit alarm screen, click the `at` button to set a before/after offset.

**Comment by forrestguice** [comment]
A few others have also inquired about this.. I think this feature might be advertised better (poor discoverability). 
For example, in previous versions of the app, the options were also available from an overflow menu.

**Comment by codeandfix** [comment]
maybe, but i dont need an alert, i just want to see the time as a value in the table like civil, nautical, etc?

**Comment by forrestguice** [comment]
thanks for clarifying.
yeah, it isn't currently possible.

I think a general feature might be the ability to add custom fields, which can then be toggled in the table, shown in a widget, or assigned to an alarm/notification, etc. These fields could be some arbitrary elevation (custom twilight event), or degree offset some event (#522), or an offset in minutes (as suggested here).

**Comment by codeandfix** [comment]
yes, just an offset to an existing time and a custom name in the list would be enough.

means: myTime = civil +1.5h 
and this value should be shown next to the other items like civil, natical, etc.

**Comment by codeandfix** [comment]
completed, but how can i set it up??

**Comment by forrestguice** [comment]
Apologies. I have some bad news. It seems I actually marked this complete by mistake in the process of releasing the "custom events" feature. I even wrote out a short explanation explaining how the UI works before realizing my mistake. :\

The good news is "custom events" makes a ton of progress toward this. It can be included in an upcoming patch (most likely `v0.15.4`).
