### ISSUE TITLE
Updates too regularly

### ISSUE THREAD

**Issue by activedecay** [forrestguice/SuntimesWidget#555]
Love the app!

Hate the constant updates that F-Droid notifies me of every time there's an update. Maybe this is just a me-problem, and I have something not configured correctly.

Can you reduce the frequency of updates?

**Comment by forrestguice** [comment]
How frequent is too frequent? 

I don't like to make contributors wait, which is why patches are typically on a 2 week cycle (if there are changes). Also, the last minor release (v0.13.0) was over a year ago.

**Comment by activedecay** [comment]
I understand. Perhaps I can just disable automatic updates on my F-Droid

Thank you for responding, though. I don't know exactly what a good number would be, but holy moly you are churning out code like there's no tomorrow. That's great for you! I'm just one of those types who get easily annoyed.

Really love your app tho. Cya!
