### ISSUE TITLE
App crashes on location icon

### ISSUE THREAD

**Issue by aWildHuman** [forrestguice/SuntimesWidget#556]
When updating or selecting current location, app crashes. This is new behavior introduced with 0.14.0 update.

**Comment by forrestguice** [comment]
I think 'current location' might be one of the app's least tested features - I typically have this set to 'user defined' and so failed to notice this.

Thank you for reporting. I'll fix this asap.

**Comment by elgorro** [comment]
@forrestguice When is it going to publish in F-Droid, because the crash is very annoying?

**Comment by forrestguice** [comment]
@elgorro Usually within a week of tagging a release, but its not something I have any control over.

**Comment by forrestguice** [comment]
@elgorro It's on F-Droid now. They seem to be getting quicker all the time. We can monitor the build process from their [status page](https://monitor.f-droid.org/builds), or by looking for the app's last [buildlog](https://monitor.f-droid.org/builds/log/com.forrestguice.suntimeswidget/85).

**Comment by elgorro** [comment]
Works fine again. Just had to change timezone from "actual time" to system.
