### ISSUE TITLE
Display the sun position dialog by hitting the sunrise/sunset area

### ISSUE THREAD

**Issue by xandro0777** [forrestguice/SuntimesWidget#562]
.. just like it works for the moon. Not only would it save me from going through the menu but seems more intuitive than searching it in the menu.

**Comment by forrestguice** [comment]
Tapping the bar graph that appears on each card should open the dialog as you describe (look in `Settings -> User Interface -> Show Light Map` if its missing).

I think it also makes sense to add the same action when the `solar noon` field is tapped. The sunrise/sunset header icons currently jump to those events, but perhaps that should be configurable.

**Comment by xandro0777** [comment]
> Tapping the bar graph that appears on each card should open the
> dialog as you describe (look in `Settings -> User Interface -> Show
> Light Map` if its missing).

ok, missed this.

> I think it also makes sense to add the same action when the `solar
> noon` field is tapped. The sunrise/sunset header icons currently jump
> to those events, but perhaps that should be configurable.

didn't notice till now but it is a bit surprising that sunrise/sunset
and moonrise/moonset icons have different functionality when hit. The
action when tapping the "next event" also seems less than intuitive for
someone who doesn't do it every day. Perhaps tapping the "next event"
could popup an overlay with events to select?
