### ISSUE TITLE
How to disable percentage in the moon phase view

### ISSUE THREAD

**Issue by treasuretron** [forrestguice/SuntimesWidget#563]
I updated to the latest version just now and now I can't get rid of the % in 1x1 moon view. Before the update it just showed the phase without the text.

I'm on a Palm PVG100 with Android 8.1.0

thanks!

Before:
![Screenshot_20220218-143720](https://user-images.githubusercontent.com/679113/155621686-5df16a42-8809-43fb-90f0-888a9828d83b.png)

Now:
![Screenshot_20220224-175328](https://user-images.githubusercontent.com/679113/155621725-8e27a81a-c7f7-4e8d-a95b-2c4911b668fe.png)

Settings:
![Screenshot_20220224-180031](https://user-images.githubusercontent.com/679113/155622076-549765d0-aa15-4d88-8b4b-64c4b282496d.png)

**Comment by forrestguice** [comment]
I'll take a closer look - it looks like a bug.

In the past that % text was controlled by the 'show labels' option, but I see its unchecked. I just tried switching between the `1x1` layouts - choosing the "moon phase only" and unchecking "show labels" should produce the icon only, but its not working for me anymore. :\

**Comment by treasuretron** [comment]
ah alright, thanks for looking into it! :)

**Comment by treasuretron** [comment]
I've updated to version 0.14.4 and am still having this issue

**Comment by forrestguice** [comment]
Please confirm that the 1x1 layout is set to "moon phase only" and that "show labels" (under general) is unchecked.

The other variations always show illumination, and the difference between "phase and illumination" and "illumination only" is the addition of the label (toggled by "show labels"). For just the icon you need "moon phase only" with the label turned off.
