### ISSUE TITLE
Regression: sunrise and sunset 17 minutes off since last release

### ISSUE THREAD

**Issue by xandro0777** [forrestguice/SuntimesWidget#565]
Hi, updated to latest version on F-droid recently and noticed both sunrise and sunset are approximately 17 minutes too early. Strangely, the sun position is displayed perfectly correct when I compared it with another program. So it looks like Sunrise/Sunset times are displayed for a place some degrees east from here.. I am at 10.9 East.

Very similar error is for moonrise and moonset.

However the geographic position is correct and did not change. I am wondering if I applied some wrong setting but am not aware of changing anything.

**Comment by forrestguice** [comment]
The code hasn't changed in that regard, so its unlikely a regression. More information is required (a screenshot goes a long way). What was the last version to work correctly (v0.13.19)?

Please verify that `Settings -> General -> Use Elevation` is checked. I think this would be the most obvious reason for the difference. 

It might also explain any difference you see in sun/moon positions - those are positions observed at sea level - I've noticed the underlying library doesn't apply the altitude refinements. The (lightmap) bar graph does though, which results in a bug where they are mismatched.

**Comment by forrestguice** [comment]
Also possible its a timezone bug. If you were seeing times reported in solar time those would be offset; `local mean` by some minutes from the timezone boundary; and `apparent solar`  offset again by the eot (currently -11m 49s).. so 17min seems reasonable for either.

Anyhow, if I saw a screenshot I could probably figure it.

Anyhow, If I saw a screenshot I could probably figure it out.

**Comment by forrestguice** [comment]
ok. I think I've reproduced this. It would seem its something I inadvertently introduced in the last patch. For whatever reason `v0.14.1` changes the configured time zone to `local mean` from whatever it previously was.

After a fresh install of `v0.14.0` I see the expected sunrise/sunset times, but after an update to `v0.14.1` those times are 26 minutes off - that just happens to be the distance from my current position to the time zone boundary. I wouldn't say its an outright bug - it does say 'local mean time' under the current time - but the change of configuration is unexpected.

So changing the time zone (back to whatever it was) should "fix it".

**Comment by xandro0777** [comment]
Ok, glad you found it so fast. Did not notice the Local Mean Time or maybe thought it was just another word for local time zone.

Related problem, when trying to set the time zone to local time zone it doesn't offer me the choice of central European time .. or at least I don't see it anywhere.

Finally - what does the "use elevation" mean. I have my own program doing this calculations and when implementing it I had a similar elevation term - the meaning of it was "if you are elevation meters above the ocean" meaning the sunset will be later because the horizon is lower. Judging by the magnitude of the effect when I enable it in this app this is how the app interprets it?

There are other effects of the elevation like refraction because of air density and temperature but those would never result in a time difference of 4-5 minutes at 300m.

**Comment by forrestguice** [comment]
That's also my understanding - sunrise is a few minutes earlier, and sunset a few minutes later, with any altitude, and vice versa for those weird spots that are below sea level.

What "use elevation" actually does depends on the [underlying library](https://github.com/forrestguice/SuntimesWidget/wiki/Help#data-sources). When checked the app passes the configured elevation to the library (and when its unchecked it passes 0).

The default [time4j](http://www.time4j.net/javadoc-en/net/time4j/calendar/astro/StdSolarCalculator.html#TIME4J) claims to take refraction into account, but I can't really comment on the specifics. At peek at the [source](https://github.com/MenoData/Time4J/blob/master/base/src/main/java/net/time4j/calendar/astro/StdSolarCalculator.java) itself might be helpful.

**Comment by forrestguice** [comment]
hrm. `CET` should be in the list, but maybe its missing. It might also be "lost in the list" .. sorting by offset is the best way to find whats available (tapping the `Time Zone` label should open a menu). Also using `System Time Zone` is always a safe bet.

The app doesn't ship an up-to-date list of time zones (but it could). The current list is whatever the Java [TimeZone](https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getAvailableIDs()) class reports.

**Comment by xandro0777** [comment]
I am probably searching the time zone in the wrong place because it doesn't show me any of this. I see only LTST, LMT, LMST, GMST, UTC.. but can't find any other place where to set it.

**Comment by forrestguice** [comment]
There should be two drop-downs; set `mode` to `System Time Zone` or `User Defined`.

**Comment by yump** [comment]
Thank you for fixing this. In case anyone else using similar search terms to me runs across this bug: on my machine, the offset was more than one hour, because Local Mean Time apparently does not include daylight savings.
