### ISSUE TITLE
Feature Request: Weekly recurring alarms

### ISSUE THREAD

**Issue by SepticFuddy** [forrestguice/SuntimesWidget#569]
I'd like to request the ability to schedule a recurring weekly alarm based on sunset/twilight times. Currently it does not appear to be an option. It would be really handy for religious observances.

Thanks

**Comment by forrestguice** [comment]
Its possible I misunderstand, but this should already be supported.

Try this.. add an alarm for sunset, then from the "edit alarm" screen, tap `no repeat` (to bring up the repeat dialog), and slide the toggle to the right (to "repeat daily"), and then tap on each of the days until only one is selected.

The alarm should be scheduled for sunset on the given day, and then later when rescheduled, for a week later, and so on. It takes a few clicks, and doesn't say "repeat weekly" anywhere, but is this functionally the same?

**Comment by SepticFuddy** [comment]
You are absolutely correct. I only got the app recently and never got past the first step of adding alarm to see that there was a second page with so many more options. I'm not sure what benefit there is to not going directly to that full edit page, but in any case it does have what I'm looking for. Thanks!
