### ISSUE TITLE
 Add Liberapay to the donate options

### ISSUE THREAD

**Issue by ghost** [forrestguice/SuntimesWidget#574]
I avoid PayPal totally and I'm probably not the only one. 
Would be very nice, I would like to donate, because you do very good work, I love your suntimes and suntimes related apps. 
Here's the link: 
[https://liberapay.com/](https://liberapay.com/)

Best regards.

**Comment by forrestguice** [comment]
It's been awhile since I've investigated the options - I'll take a look at Liberapay. I'm not really sure I'm comfortable with its recurrent nature, but I'm not a big fan of Paypal either. I can completely understand aversion to it.

**Comment by bonheurrosa4** [comment]
how's that? the aversion to paypal

**Comment by bonheurrosa4** [comment]
> It's been awhile since I've investigated the options - I'll take a look at Liberapay. I'm not really sure I'm comfortable with its recurrent nature, but I'm not a big fan of Paypal either. I can completely understand aversion to it.

how's that? (aversion to Paypal)

**Comment by forrestguice** [comment]
@bonheurrosa4 It gets criticized for lack of privacy. Indeed, as the receiver, I see the real names (and other information) of donators.

**Comment by hacksenwerk** [comment]
@forrestguice About the recurrent nature, the FAQ says: 
„Can I make a one-time donation?
One-time donations aren't properly supported yet, but you can discontinue your donation immediately after the first payment.“

Maybe the option for a SEPA bank transfer would be possible too at github?

**Comment by Friptick** [comment]
> SEPA bank transfer

Great privacy against 3rd parties but none at all against 2nd. Liberapay seems the right balance.
