### ISSUE TITLE
Cannot find Available Data Sources

### ISSUE THREAD

**Issue by NKentatE** [forrestguice/SuntimesWidget#581]
I cannot find available data sources option in suntimes app since Version 14. Please fix it.

https://github.com/forrestguice/SuntimesWidget/wiki/Help#available-data-sources

**Comment by forrestguice** [comment]
As far as I know there is nothing to fix.. Its in General settings, where its always been, but now at the bottom of that page under the heading "Advanced". If its actually missing, a screenshot would be helpful.

I'm confused though - how did you reach that URL if not through the help button in the app? Its an advanced option - there isn't much point in changing it away from the defaults without reason. I didn't think anyone actually relied on this feature.

**Comment by NKentatE** [comment]
Yes its available.
Big gab between general and advance in general i will not seen.
I am sorry for make this issue.

**Comment by forrestguice** [comment]
> I am sorry for make this issue.

Please don't be - whenever somebody is confused by something, its a good opportunity to make some UX related improvement. 
We can reduce that gap so the setting doesn't seem hidden.

**Comment by NKentatE** [comment]
Thank you
