### ISSUE TITLE
Some better way to select events tracking

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#590]
This is a really minor thing.

Go to `Tropical Year` → `⋮` → `Track` and we have this:

![](https://user-images.githubusercontent.com/982338/165358387-3a454fbc-5d25-4bb4-8a60-da170873b661.png)

At least for me, it seems to be a checkbox, which allows multiple options to be selected at the same time (while, in fact, it isn't).

Maybe the options could be displayed in another way?

**Comment by forrestguice** [comment]
Right. These should be radio buttons.

It seems the difference in code is subtle; using `<group android:checkableBehavior="single">` is all that's needed to display the menu items as radio buttons, but adding `android:checkable="true"` overrides that. This mistake shows up in a few other menus.
