### ISSUE TITLE
Two %substitutions for Sun Widgets [Feature request] 

### ISSUE THREAD

**Issue by Timo-Fi** [forrestguice/SuntimesWidget#599]
Could you please consider adding the following two item into the %substitutions group of Sun Widgets. 

a) Local time at the moment of the solar noon (hh:mm would be enough)
b) Elevation angle of the sun at the moment of the solar noon (one decimal would be enough)

This pair, that tells the solar noon elevation degree, and at what local time it happens, helps sunbathers in arranging the sunbathing duration(s) easier.  

The (a) is currently available as an 1x1 sun widget, but having this information on the Title line of a sun widget removes the need to have an 1x1 widget just for the purpose of showing it. So, makes the homescreen layout more stylish. 

The (b) is shown amongst the items of "Labels" in the 3x1 sun widget, but  the "Show labels" checkbox does not bring the labels visible on the rectangular world map in 3x2.

**Comment by forrestguice** [comment]
Seems like a good workaround to the problems identified - I've made this a last minute addition to `v0.14.5`. It should be on F-Droid later in the week.

The new %substitutions are `%em` (event timestamp (millis)), `%et` (formatted event time), `%eT` (include seconds), and `%eA` (angle of event). A `@` qualifier is expected afterwards to identify the specific event. 

For example..

| pattern | description |
|------|------|
|%et@ar|Astronomical rise|
|%et@nr|Nautical rise|
|%et@b8r|Blue Hour rise (8deg)|
|%et@cr|Civil rise|
|%et@b4r|Blue Hour rise (4deg)|
|%et@gr|Golden Hour rise|
|%et@sr|Sunrise|
|%et@sn|Solar Noon|
|%et@ss|Sunset|
|%et@gr|Golden Hour set|
|%et@b4s|Blue Hour set (4deg)|
|%et@cs|Civil set|
|%et@b8s|Blue Hour set (8deg)|
|%et@ns|Nautical set|
|%et@as|Astronomical set|

Maybe overkill I suppose, but it was actually easier to implement it uniformly for all events (vs special behavior for just noon).

All of these should work with the "sun position widgets", but the ordinary "sun widgets" are limited to `sr`, `sn`, and `ss` (mapped to the underlying dataset). Similar, these won't work with the non-sun widgets as that data isn't available there. It highlights a limitation of the widgets (each is defined/limited by its data). Fortunately the sun position widgets already require multiple datasets, so its already in a position to offer all this information.

**Comment by forrestguice** [comment]
> This pair, that tells the solar noon elevation degree, and at what local time it happens, helps sunbathers in arranging the sunbathing duration(s) easier.

When explained this way, it makes sense to me to also add a `1x1` widget that displays this pair.
