### ISSUE TITLE
Full moon

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#600]
Hi @forrestguice ,

I can see the full moon in the sky today ,
But the app say it will be in 16-5 at 6:14 am

Egypt

**Comment by forrestguice** [comment]
It's true; the instant of the full moon is ~6AM on the 16th (https://www.timeanddate.com/moon/phases/egypt/cairo)

It appears full (98-99%) a day or two before and after though. I think this is same/similar confusion discussed in #345?

**Comment by islam2hamy** [comment]
sorry for duplicate ,
yes i think so
