### ISSUE TITLE
First Time Install Experience

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#603]
> I use this opportunity to explain my experience(s) about 1st time installation of the Suntimes, I've done a clean install well over ten times. In my opinion it is not overly smooth, to the extent that it possibly can rather easily upset a new user.  First one has to understand that it is the current location that needs to be specified. Then one has to find the Location dialog, where the default mode is "User Defined': Phoenix, but it can not be removed by the means provided in that dialog. Next one gets the bright idea to change the mode to 'Current (last known)', but unfortunately it does not help any. Then one may tap the 'update' textlink,  and it usually (as there is no gps fix indoors) just dismisses the Location dialog, which can be mind baffling.  So, is there not, inside the  Android somewhere, some kind of location data available to be used at the time of 1st install, just a coarse location (or network derived location) at this point would help a great deal. There surely is in Android the system time zone data. If these could be used automatically as the default setting for clean install, it would be way better for the 1st time user. My approach to this is to open the 'My Location' app by Mirfatif (from F-Droid), go outdoors, monitor the app until it show that gps fix has been achieved. Then switch back to Suntimes and update the gps location in the Location dialog, and finally go back indoors to continue settings.  I always set the 'GPS recent max age to 'any age' so after it is once got it never vanishes. 

_Originally posted by @Timo-Fi in https://github.com/forrestguice/SuntimesWidget/issues/601#issuecomment-1128066944_

**Comment by forrestguice** [comment]
@Timo-Fi I've copied this here. Its definitely worth addressing as its own issue.

btw, I'm reminded of a "User Interfaces" project years ago at University. We were required to "test" our final UI by recording pairs of volunteers trying to use our software to accomplish some task. We gave them a basic script (what to do, but not how), left the room, and let them struggle for 20 minutes (later revealed in the video).

**Comment by Timo-Fi** [comment]
I already made a post to the earlier chain, then found this.  I'd say that even a short/dense help page could be beneficial.  In the the style that the "Total Commander for Android" app has it. A very back-to-the-basics page, accessible from the three dots on the main menu. Once I master the Suntimes I'll write one.
