### ISSUE TITLE
Minor glitch in creating a new notification

### ISSUE THREAD

**Issue by Timo-Fi** [forrestguice/SuntimesWidget#605]
**To Reproduce**

1. Start making a new event (or time) notification.
2. Set up the 1st page and press OKwedge.
3. On the 2nd page, tap on the the event type (or time) in the attempt of altering it.
4. That 2nd page disappears, the alarm list is shown instead but without the AddNew -icon at the lower right.

**Expected behavior**

Change of the event type (or time) should happen (in v.0.14.4 it does so)

**Version Info:**

- App Version:  0.14.5
- Android Version:s 7.0 and 11

**Note**

New notifications can be made, one just needs to enter the event type (or time) properly on the 1st page. (I have previously created new notifications by just tapping the OKwedge on the 1st page and then configured it all in on the 2nd page).

**Comment by leonenethz** [comment]
I have the same issue after updating to the newest version. I can set an alarm, but if I tap on the Icon of the event where it says "hh:mm Clock Time" I can't change the time or event it just switches back to the overwie of my set alarms.

**Comment by forrestguice** [comment]
Thanks. It seems 36f8c4e12cb488e9dd2e5dd1fc535604dadcd991 fixes one bug, then adds another..
It'll be fixed in the next patch.
