### ISSUE TITLE
alarm list is not sorted after adding items

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#609]
**Describe the bug**
Alarms are not added to the alarm list in sorted order.

**To Reproduce**
1. Add an alarm or notification (if the list is empty, add several).
2. Observe that each item is added to the bottom of the list.
3. Sort by 'Creation Date' (or trigger sort by restarting the app, or rotating the device).
4. Observe that the list is sorted; recently created items now appear at the top (not the bottom).

**Expected behavior**
The list should remain sorted after adding items.

**Version Info:**
Tested with `0.14.6`, but probably present all the way back to `v0.13.0` when ability to sort was added.

**Additional context**
Since a sort is triggered whenever the app (re)starts the issue is transient. IIRC the app originally sorted by creation date, with recent items appearing at the bottom.

**Comment by Friptick** [comment]
Can confirm this.
