### ISSUE TITLE
Confusing UX on alarm list

### ISSUE THREAD

**Issue by Friptick** [forrestguice/SuntimesWidget#611]
The UX on the alarms list is problematic.

Steps to reproduce:
1. Go to Suntimes Alarms
2. There is a list of alarms (or notifications): `00:30` `14:08` `20:22`
3. Tap `14:08` - it toggles to displaying `3 hours before 17:08`. Now the list shows alarms in confusingly different formats. It's not certain when the next alarm is.
4. Tap the alarm again to untoggle the different format - you get the alarm edit dialog instead. Cue frustration!

**Expected behavior**
A list of alarms should probably not show times in different formats simultaneously. Too confusing. Possible solution: a global toggle to show _all_ the alarms in `xx:xx` format or `x hours before xx:xx` format.

**Version Info:**
 - App Version: 0.14.5
 - Android Version: 8

**Comment by Timo-Fi** [comment]
In step 4, do the tap over the "from now".   I too was a little confused about the changing representation, over the duration of some weeks, until I found that toggle. It is totally OK like this it.

**Comment by Friptick** [comment]
@Timo-Fi Well noticed! Yes, that somewhat helps. Unconvinced this is optimal though, the format still reverts immediately to one that's not the same as the others displayed as peers in the same list. Making it difficult to compare and see at a glance when the alarms are actually due to go off and in what order. I find that pretty opaque and confusing.

Another better solution might be to display the 2 formats side by side for each alarm.
- `14:11`
- `1h30 before 15:41` (small font)

**Comment by forrestguice** [comment]
I'm not sure I really agree - I actually don't see any problem here. 

Selected items are expanded, while unselected items are collapsed. Expanded items show the expanded format (e.g. 30min before) and additional controls, while collapsed items show actual alarm time, and indicate that with an "offset icon". Wherever that icon appears, tapping it toggles between the two formats. If you want all alarms in the same format, press "back" to unselect all items.

There isn't sufficient room to display both simultaneously. If there seems like lots of space, it just means you have a larger than average phone.

**Comment by forrestguice** [comment]
A toggle doesn't make sense to me - both formats are useful in their own context. The collapsed 'alarm time' is necessary to know when the alarm actually goes off, and the expanded 'offset time' to recognize and edit your own alarms. What is more confusing - displaying 30min after 6:30 and expecting users to calculate 7:00 in their heads, or simply displaying 7:00 with an icon, and then showing the expanded format when touched.

**Comment by forrestguice** [comment]
> Making it difficult to compare and see at a glance when the alarms are actually due to go off and in what order. 

Again, I disagree. All items are initially collapsed (show the same format) so its easy to make a comparison. And when sorted, the items are in chronological order, so I don't see any issue.

**Comment by forrestguice** [comment]
So, I don't like the proposed solutions.
That doesn't mean this isn't a confusing feature, or that it can't be tweaked somehow.

I think the 'offset icon' needs to be mentioned in a help dialog, so users recognize the symbol.
Maybe the list should automatically collapse items after a minute or so, returning it to a uniform format.

**Comment by Timo-Fi** [comment]
> I think the 'offset icon' needs to be mentioned in a help dialog, so users recognize the symbol. Maybe the list should automatically collapse items after a minute or so, returning it to a uniform format.

In my opinion the behavior of the list is OK just as it is.  Automatic/timed UI changes sounds very ghostly to me. Perhaps the "~ ah bm from now" could have some font color that indicates that it is a link/toggle.

**Comment by Friptick** [comment]
@forrestguice As I said elsewhere, it's your work and I'm certainly not complaining here. Just remember that, as the developer, you have an inside view of the UX which might make it hard to imagine using the app as dumb users like me will use it in practice. I hear your justifications but to me the UX is confusing. I have a list of times displayed with identical formatting but which in fact mean different times. Clicking the back button restores order, yes, but this is non-standard unguessable UX (and personally I find the back button unpredictable and problematic - half the time it closes the app, so I find myself just avoiding it in practice).

Once again, this is just feedback from a dumb user but with a ton of experience of using a ton of apps. I see that the other dumb user doesn't even agree with me, so I'm sure you'll take that into account too. :)
