### ISSUE TITLE
Mad defaults on install

### ISSUE THREAD

**Issue by rogercreagh** [forrestguice/SuntimesWidget#615]
I came very close to abandoning this as non functional after spending 10 minutes poking around trying to get it to display something close to the correct sunrise and sunset for my location.
The complete absence of help or guidance, the tiny font with colours that are almost unreadable in daylight, the confusing terminology around time zones, and the need to manually look up the coordinates for your location are all parts of the nightmare.
Please on install look up the current timezone and location from the system - hundreds of other apps manage this without problems.
Please increase the font size for the key info so it is more visible - the primary things are the time the sun and moon actually rise and set - and the direction. The other times may all be useful for particular purposes, but make them less prominent.
And pay attention to legibilty - orange text on black is not good, especially if the font is small. Black text of a sensible size on a white background.
By the way it is completely unclear what the point of the map icon is - it gives you an android dialogue to select which map app to use, but what is the point. When the map opens it doesnt seem to allow you to select a location and pass it back to this app to get the sunrise for the selected point - so why is it there?

**Comment by forrestguice** [comment]
imho, some harsh criticism here. This kind of reminds one of those Google play reviews, but I am going to assume good faith. I disagree with some of what you are saying, but I am glad to accept feedback and improve upon the app.

> tiny font with colours that are almost unreadable in daylight

I agree the app could be improved by reworking layouts and trying to fit less onto the screen. However, the default colors have all been tested for contrast and color blindness - despite your claims they are quite readable. That said, the dark theme is more mature (received more attention over time). There is nothing stopping us from introducing new themes; e.g. black on white as suggested.

> confusing terminology around time zones

Please be specific, as I can't fix this terminology if you neglect those details.

> the need to manually look up the coordinates for your location
The location is manually configured by default, and that isn't going to change. I will interpret your confusion as criticism against the configuration dialog. If you had explored it further you may have discovered the button for retrieving the system location (among other UI available).

> Please increase the font size for the key info so it is more visible - the primary things are the time the sun and moon actually rise and set - and the direction. The other times may all be useful for particular purposes, but make them less prominent

Review the app's user interface settings. You will discover that its possible to toggle the visibility of ALL fields. It is also possible to define alternate colors, and define font sizes. Theming is a rough experience though (themes were actually designed with widgets in mind).

> By the way it is completely unclear what the point of the map icon is 

It opens the configured location in the system's map app - it displays the configured location. Its also possible to go in the other direction - by opening a map app and using it to "share" a location with Suntimes. This app can be thought of as a "GPS companion", in that becomes more useful when combined with other (mapping) apps. That said, I think there should be an option to toggle the icon (just like there are options for everything else).

> I came very close to abandoning this as non functional

You do what you are going to do. I'm happy to accept feedback and improve the app, but please don't misunderstand my motivations - I primarily develop software for myself.

I found this report difficult to read. It's not what was written, but how those ideas were expressed. Honestly, I'm finding maintenance (8 years of it now) to be emotionally draining. There will always be something wrong, something that needs to be fixed. That is just the nature of software development, and I'm happy to work on those issues. However, I would ask that you please work on your communication skills. I'm not looking forward to replies if they are anything like the original post, but I won't discover problems by closing my ears (and software /always/ has problems).

**Comment by rogercreagh** [comment]
Thanks for the email reply and for taking the trouble to understand the criticisms in the spirit they were intended - unfortunately the email has disappeared so just leaving a brief note here to thank you for responding.
