### ISSUE TITLE
callback compatibility issue when initialing method 

### ISSUE THREAD

**Issue by PSDroid2022** [forrestguice/SuntimesWidget#621]
We confirm a callback compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''com.forrestguice.suntimeswidget.LocationConfigView", you super the framework API "<android.view.View: void onVisibilityAggregated(boolean)>" in "onVisibilityAggregated" method as shown in following, which is implicit invoked by the Activity "SuntimesConfigActivity0". But actually, this method is added in API level 24 (
https://developer.android.google.cn/reference/android/view/View?hl=en#onVisibilityAggregated(boolean)).

```java

    @Override
    public void onVisibilityAggregated(boolean isVisible)    // TODO: only called for api 24+ ?
    {
        super.onVisibilityAggregated(isVisible);
        if (!isVisible) {
            cleanupAdapter();
        }
    }
``` 
So when the app try to initial related funtion on devices level 16 ~ 23, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT>= 24)" or change your app miniSDK from 16 to 24 to fix this potential issue. 

## Android device

 - Device: [e.g. Emulator]
 - OS: [e.g. API 16~23]
 - Suntimes Version: [0.14.7]

**Comment by forrestguice** [comment]
AFAIK `onVisibilityAggregated` isn't called on these device levels (and so the call to super is harmless). They will run `onVisibilityChanged` instead. I don't see any harm in checking `SDK_INT`, but maybe a better solution is to annotate the entire thing @TargetApi(24).

How are you detecting these issues?

**Comment by PSDroid2022** [comment]
Actually, this annotation only suppresses the compiler's warning (i.e., Lint). It will be deleted in the apk package. And when this API is called before API 24, the app will still meet a crash. So we suggest add a SDK version check before invoke the API. (https://stackoverflow.com/questions/40007365/requiresapi-vs-targetapi-android-annotations)

Hi, we detect these issues by traversing the call graph and control flow graph of Suntimes.

**Comment by forrestguice** [comment]
> Actually, this annotation only suppresses the compiler's warning

The compiler isn't currently issuing a warning. That is why I'm curious as to your methods.

> when this API is called before API 24

And when does that happen exactly? I don't think it does. Anyways, look closely at those lines and suppose the call to super is protected by an `if (SDK_INT)`; does that actually satisfy the requirement that super is always called.

You are telling me the app will crash, but I'm still not convinced there is an actual problem here.

**Comment by PSDroid2022** [comment]
1. As we know, Lint will report false negatives in some conditions.
( https://stackoverflow.com/questions/44284188/false-positive-in-android-lint-check-for-linkedhashmap-remove )

2. The super method also invokes compatibility issues when initial the method which is called callback compatibility issues. (
https://search.ahnu.cf/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjqhZK1kuj5AhVELkQIHUPcB_IQFnoECAQQAQ&url=http%3A%2F%2Fcastle.cse.ust.hk%2Fandrewust%2Ffiles%2FASE18-Cider.pdf&usg=AOvVaw1TTgmhdWguPa85ZMKA6RnX)

3. We also find such callback issues in other projects.
(https://github.com/enricocid/Music-Player-GO/issues/383#issue-1169297700)

**Comment by forrestguice** [comment]
Sorry but none of that is convincing. The first link doesn't actually describe 'false negatives' as it does 'false positives', which is exactly what I think you are reporting. The second link isn't accessible to me (404). The third link really doesn't tell me anything - that you are finding similar issues across many project does little to convince me there is any danger of `onVisibilityAggregated` actually being executed on older devices. If I understand the linked describing the problems with @TargetAPI, I should instead be using @RequiresAPI instead as it actually enforces the restriction and will prevent me from making an explicit call (which isn't actually happening).

**Comment by PSDroid2022** [comment]
Hi, we update the link.
1. Lint doest not support to detect intermediate method call.(https://dl.acm.org/doi/10.1145/3417113.3422188)
![图片](https://user-images.githubusercontent.com/57435804/187051603-60a4fcfb-bd88-4a76-aa02-db41f054f195.png)

2. Understanding and Detecting Callback Compatibility Issues for Android Applications
https://ieeexplore.ieee.org/document/9000066

**Comment by forrestguice** [comment]
Thanks. I do understand that.

This issue is specific to `onVisibilityAggregated`. Can you please provide details why you believe this method will be called for api < 24. If not, I'm going to close this issue. I don't think the recommended suggestions actually fix anything, and I suspect wrapping the call to `super.onVisibilityAggregated` actually has the potential to cause problems, not fix them.

**Comment by PSDroid2022** [comment]
Hi, following shows an example.
```java

    @Override
    public void onVisibilityAggregated(boolean isVisible)    // TODO: only called for api 24+ ?
    {
     if(SDK_INT>= 24)
      }
        super.onVisibilityAggregated(isVisible);
        if (!isVisible) {
            cleanupAdapter();
        }
      }
    }
```
This issues seems not leading a crash for app, but it's not nice to keep an unnecessary thread running and consuming the system resources.

**Comment by forrestguice** [comment]
> it's not nice to keep an unnecessary thread running and consuming the system resources

What are you talking about?

**Comment by PSDroid2022** [comment]
--!
It's not nice to keep an unnecessary code running and consuming the system resources

**Comment by forrestguice** [comment]
I'm quickly losing patience.. :\ Please identify the code you believe is running unnecessarily.

`onVisibilityAggregated` is a function that was added in api24 (and is not run by earlier devices). It's unclear how the required call to `super` is going to crash the app on devices that don't run that code. The only reason to wrap it in an if(SDK_INT) would be to allow the app to compile. IMHO the current lint tools do a fine job identifying these issues.

I do appreciate you taking time to file issues on this tracker. However, I think in both cases you've just stumbled onto "false positives". I get the impression this is a research project which is being conducted using tools you've developed yourself. I wish you luck with that - its not the first time someone has identified "code smells" here, and probably won't be the last.

I will be on the lookout for an actual crash, but until then I don't believe any action needs to be taken.

**Comment by forrestguice** [comment]
> It's not nice to keep an unnecessary code running and consuming the system resources

Maybe you are referring to the behavior on api<24. As mentioned, those devices don't run this code, they run `onVisibilityChanged` where a similar call to `cleanupAdapter` takes place. There aren't any circumstances where there is "an unnecessary thread running and consuming the system resources". As far as I know its handled in all cases, verified by actual testing. If you have evidence contrary to that, then I'm glad to act on it. Otherwise it just amounts to an unfounded assertion.

**Comment by PSDroid2022** [comment]
OK，thanks！
