### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [forrestguice/SuntimesWidget#637]
We are building on Debian bulleye now with jdk 11. Could you please bump the gradle to 5 to support jdk 11? Thanks!

**Comment by forrestguice** [comment]
Hi @linsui, thanks for letting me know. :( It's a major inconvenience to say the least. 
Does F-Droid no longer support building for older versions?

I will need to refactor some stuff (switches replaces with ifs, etc), so it seems its not as easy as just bumping the version.

Does upgrading to gradle 5 necessitate upgrading the android plugin version and support libraries? These are currently locked to `3.1.2` and `25`. I was planning on making build changes as part of the `1.0.0` release, planned immediately after `v0.15.0` (which was to be the last version built for legacy devices).

**Comment by forrestguice** [comment]
> Does upgrading to gradle 5 necessitate upgrading the android plugin version and support libraries?

I guess it doesn't but for some reason I thought it did. The project still builds after bumping the version, so I think all I need to do is fix those switch statements and its good to go.

I would like to avoid tagging another version - supposing I delete and re-tag `v01.4.9`, will F-Droid be able to pick up that change?

**Comment by forrestguice** [comment]
Actually, I think I've misread those warnings about using `switch`. They apply to "Android Gradle Plugin version 5.0", not Gradle 5. Unless I'm missing something else, it seems this really was as easy as just bumping the version.

**Comment by linsui** [comment]
> I would like to avoid tagging another version - supposing I delete and re-tag v0.14.9, will F-Droid be able to pick up that change?

You just need to push the commit. The tag is only needed for auto update.

> Unless I'm missing something else, it seems this really was as easy as just bumping the version.

Yes, it's mostly backward compatible. Thanks!
