### ISSUE TITLE
Widget updating improvement

### ISSUE THREAD

**Issue by Timo-Fi** [forrestguice/SuntimesWidget#649]
Hi, the new 'Update All Widgets' option works generally nicely, but like in the situation as shown by the screenshot: The widget id53 shows the sun altitude  as -10.9° but the id:72 shows -10.6°. The  id53 has 'On Tap 'action 'Suntimes', the id72 has 'Update All Widgets'.  What happens is that a tap on the id72 does the updating properly OK, but a tap on the id53 only updates itself (as seen when I return to homescreen).  

An other things, that really does mot matter at all, is that in the id57 the substitution "%loc" does not show the coordinate values on the title line, just the 'Last Position' is shown. 

EDIT: In addition, could it be possible to have a substitution for the value of the Equation of Time?
 
![X1-2022-11-21-1729](https://user-images.githubusercontent.com/75567840/203095536-12bd1278-349f-4fef-bca2-3607b933b5ab.png)

**Comment by forrestguice** [comment]
It should now be possible to tweak the 'On Tap' for id53 to also 'update all' (in addition to launching the app). Configure 'On Tap' to 'Perform Action' 'Suntimes'; then expand the editor (`v` icon on left side ), and set the "Action:" field to `suntimes.action.widgets.UPDATE_ALL`. The auto-complete should try to help.

> the substitution "%loc" does not show the coordinate values 

`%loc` should be location name only, and `%lat` and `%lon` for the coordinate values. Unless I'm misunderstanding, its `%loc: %lat,%lon` instead.

> could it be possible to have a substitution for the value of the Equation of Time

This is also in `v0.14.11`.
`%eot` for "formatted 'equation of time'", and `%eot_m` for the millisecond value (just in case its useful as part of an action somehow).
