### ISSUE TITLE
unable to disable alarm reminder notification

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#650]
**Describe the bug**
The "reminder within" alarm preference fails to display the "never" option, making it impossible to disable the reminder notification.

**To Reproduce**
1. `Settings` -> `Alarms` -> `Reminder within`
2. Scroll to the very first entry (past 1); it should be `never`.
3. Observe; the first entry is actually `1` ("never" is missing)

**Expected behavior**
The preference should allow disabling the notification.

**Version Info:**
 - App Version: v0.14.10
 - Android Version: 10, 12

**Additional context**
It works as expected on an older device running 4.4.4, but fails on a newer device running Android 10, and on the emulator running Android 12. This bug was reported in #628.

**Comment by forrestguice** [comment]
I wish I could remember what I was thinking ~3 years ago.. I should have written it down. For some reason this was intentional - alternate resources were added for v21+ (when the feature was introduced).

**Comment by cubetronic** [comment]
I just experienced this issue. I have never wanted an upcoming alarm notification for anything. Upcoming alarm notifications are absurd.

An upcoming alarm notification goes off when I don't want it to. And the only way to get rid of the false alarm is to tap dismiss, which disables the correct alarm.

I'm unable to swipe-away the upcoming alarm notification. It takes up screen space and drawer space. I'm very much looking forward to the fix.

F-droid is several versions behind. Please release an apk. I do not use the Play store. Thank you.

**Comment by forrestguice** [comment]
> F-droid is several versions behind. Please release an apk.

You are mistaken. The most recent release is `v014.10`, and that is what is available on F-Droid. If it fails to show up you need to refresh your index. I also don't use Play store, but I'm not sure what that has to do with anything - Suntimes isn't published there.

**Comment by forrestguice** [comment]
> Upcoming alarm notifications are absurd.

On "modern Android" they are definitely superfluous. On Android 5+ there is a dedicated spot in the tray for upcoming alarms, so I understand why an additional notification is unwanted.

It was originally for older devices, then later enabled for all devices, since the notification also allows dismissing/rescheduling repeating alarms early (something that is missing from the UI).

With `v0.14.11` it should be possible to disable it, and the preference dialog adds a "Never" button to make this easier. Also, it should now be possible to swipe the notification away.
