### ISSUE TITLE
[Feature request] Accessibility issues in GUIs

### ISSUE THREAD

**Issue by Kazaf123** [forrestguice/SuntimesWidget#656]
**Description**
This is a feature request about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
<img width="360" alt="MuMu20221128085608" src="https://user-images.githubusercontent.com/44084361/204170372-66e66fcc-3721-479c-bf4c-8fc5ac2f3415.png">
**Content**
After I applied my proposed tool to detect the content page, I discovered the text in this GUI could not be enlarged, which is hard for low-vision users to see clearly. So, I sincerely struggled you could repair these issues so that visually impaired users would use this App more conveniently.

**Comment by forrestguice** [comment]
Thanks for the report. I appreciate your concern over accessibility issues. 
The text in the screenshot is `12sp` which is definitely too small for many people. I think the recommended minimum is `14sp`.

I've received a few similar reports, and hope to fix the problem in `v0.15.0`. 
It will increase the default size to `14sp`, and will add a "Text Size" option (`small`, `normal`, `large`)  to increase the size further.

The current version `v0.14.10` should respect the "Large Text" accessibility settings (and scale text appropriately), but the scaled text is still relatively small. The current version should also work with features like "Talk Back", but its poorly tested.
