### ISSUE TITLE
Moon widget disappeared after update to 0.15.0

### ISSUE THREAD

**Issue by sphh** [forrestguice/SuntimesWidget#689]
**Describe the bug**
With the latest update from 0.14.12 to 0.15.0 I get a "Problem loading widget error" for my moon widget, which just shows the moon and the percentage.

**To Reproduce**
1. Install version 0.14.12.
2. Add the widget, which just shows the moon and its percentage to the home screen.
3. Update to version 0.15.0.
4. Instead of the widget displaying the moon, I get a "Problem loading widget error" error.

**Expected behavior**
The widget added in versions prior to 0.15 should still show after an update.

**Version Info:**
 - App Version: 0.15.0
 - Android Version: 8.1
 - Device Model: Unihertz

**Additional context**
I use F-Droid to install apps.

**Comment by forrestguice** [comment]
Does resizing the widget restore it, or removing and re-adding it have any effect?

I can't reproduce it on my devices, but there were changes to the widget layouts. I don't doubt there's some problem. There should be an exception / stacktrace in your logcat that should help diagnose what's happening.

**Comment by forrestguice** [comment]
Which launcher are you using? I'm wondering if its the device's stock launcher, or something else (#690 mentions lawnchair2).

**Comment by sphh** [comment]
I am using Lawnchair 2.0-2589.

When I add a new Suntimes Widget, I experience the same behaviour as described [here](https://github.com/forrestguice/SuntimesWidget/issues/690#issuecomment-1423709269). For me it looks like those two issues are duplicates. (Feel free to close mine, because #690 goes into more detail.)

**Comment by forrestguice** [comment]
Thanks for the details. 👍 
It is the same as #690
