### ISSUE TITLE
widget doesn't work since 0.15.0

### ISSUE THREAD

**Issue by Joppla** [forrestguice/SuntimesWidget#690]
**Describe the bug**
Widgets don't work anymore. In the previous version they do.

Android 11, lawnchair2 launcher

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Version Info:**
 - App Version: [e.g. 0.14.3]
 - Android Version: [e.g. 10]
 - Device Model: [e.g. Pixel 6]

**Additional context**
Add any other information about the problem here.

**Comment by Joppla** [comment]
#689

**Comment by forrestguice** [comment]
Thanks for the report.
Unfortunately I've failed to reproduce it on my own device (a "moto e" running Android 10), so I'm not sure exactly what's happening yet. This is happening for every widget?

The cause might be device specific - if you could edit your report and supply `Android Version` and `Device Model`, those might turn out to be important clues.

**Comment by forrestguice** [comment]
I think another possibility is its somehow launcher specific - thanks for mentioning that detail - I've only tested recent changes using the default.

btw, whenever that "problem loading widget" message is displayed, there should be an exception / stacktrace added to the logcat. Getting a copy of that error message would help diagnose things.

**Comment by Joppla** [comment]
Hi my phone is fairphone4.

I tried several widgets of your app. All show the same problem. Putting on the screen it show for short moment till the setting screen opens automatically. 0.5 sec or less.

I tried several settings.

All result that after closing the setting screen I see a white place holder with message that is the same as in #689.

I turned back to  .14.? There the widget still works correct.

In the launcher I have option enlarge widgets on.

**Comment by forrestguice** [comment]
Thanks for the details. 👍 
I think this might be a bug in lawnchair (they might be interested in a report w/ stacktrace).

Its probably triggered by recent changes to the widget layouts in `v0.15.0`. Since every layout was changed in the same way, I have an idea which line is causing problems. I've reverted those changes, so hopefully this is working again with `v0.15.1`.

**Comment by Joppla** [comment]
Hi @forrestguice , 
Will the 0.15.1 published on F-Droid or have I to test the release from here?

**Comment by Joppla** [comment]
Thanks for information.
