### ISSUE TITLE
Chinese lunar calendar?

### ISSUE THREAD

**Issue by petep0p** [forrestguice/SuntimesWidget#692]
not so much an issue, and more of a feature request. i really like the new date widget with the different calendar options but i would really love to see the Chinese Yin/Xia lunisolar calendar as an option. would that be possible in a future update?

**Comment by forrestguice** [comment]
I think this should be possible.
The date widget uses the Time4J library, so its relatively easy to add other calendars supported by this library. If a calendar isn't supported, then it might be possible to get it added to the library (and eventually part of the widget).

I will add http://www.time4j.net/javadoc-en/net/time4j/calendar/ChineseCalendar.html in `v0.15.1`, but I'm not entirely sure its what was requested. Those docs point to https://en.wikipedia.org/wiki/Chinese_calendar, which mentions the Xia calendar in a historical sense, so I'm assuming this is actually a modernized version with different rules? I'm also unsure if all of the elements are "formattable" (e.g. "solar term"), so it might be impossible to display some patterns.

**Comment by petep0p** [comment]
thank you! that would absolutely fulfill my request. i don't pretend to be an expert on it, and that does seem like a more complicated calendar than some others, so whatever info you're able to add into the widget will be awesome. mainly I'd just like to see the major holidays with less guesswork and on my home screen.

much appreciated!
