### ISSUE TITLE
Sun position doesn't update on main screen in 0.15.0

### ISSUE THREAD

**Issue by Sunspark-007** [forrestguice/SuntimesWidget#695]
On the main screen showing all the times, etc. the position of the sun is not updated. It stays where it was when the app initially cold-launched.

However, the pop-up panel for the sun position DOES update.

Also appears that the main panel sun position can be made to update if you move a few days ahead and then tap on the time to return it to the current day.

**Comment by forrestguice** [comment]
Thanks for the report. I somehow missed this detail (frequently opening/closing the app).
I'll fix this soon in `v0.15.2`.
