### ISSUE TITLE
Navigation bar is white instead of black despite dark theme being selected in 0.15.0

### ISSUE THREAD

**Issue by Sunspark-007** [forrestguice/SuntimesWidget#696]
Navigation bar with the buttons for back, home, etc. is coloured white instead of black despite night mode being selected on the device and dark theme selected in Suntimes. 

This device is on Android 9.

This thread may be of assistance in fixing it: https://stackoverflow.com/questions/27348336/how-to-change-system-navigation-bar-color

**Comment by forrestguice** [comment]
Hopefully this is improved with `v0.15.1`. It should be on F-Droid in a few days.

Its not perfect though. I ran into some difficulty changing the navigation icons to match (a consequence of targeting an older api version). I'd prefer the colors were lighter/darker, but went with mid grays to avoid potential contrast problems.
