### ISSUE TITLE
[Feature request] How to view alarms?

### ISSUE THREAD

**Issue by pistacio9** [forrestguice/SuntimesWidget#699]
When I set a new alarm, I can see those existing, but I don't see how to view existing alarms without creating a new one.

**Comment by forrestguice** [comment]
Hi. There should be a "Suntimes Alarms" icon in your launcher - if its missing it can be enabled from `Settings -> Alarms -> Launcher Icon`. That should be enabled by default, but the "welcome screen" offers a way to disable it, so maybe this setting was toggled. It should also be possible to reach the alarms screen from `: -> Set Alarm` without adding an alarm (from the icon in the lower left corner). I hope this helps.

**Comment by pistacio9** [comment]
It does help. Thank you.
