### ISSUE TITLE
Time refreshes aren't happening properly in 0.15.3

### ISSUE THREAD

**Issue by Sunspark-007** [forrestguice/SuntimesWidget#705]
There are 2 time-related refresh issues happening here, both probably due to the same cause.

1) I reported the sun position not refreshing bug in https://github.com/forrestguice/SuntimesWidget/issues/695, it is better than it was before but it is still an issue. You can launch the app on a new day, the sun will be in the correct position. Come back to the app a few hours later, it hasn't changed position. To refresh it you need to switch to another day in the app then tap the clock to switch you back. 

2) To the right of the main clock, it will display something like "4h 1m until moonset" (even though the sun is in the correct position in this example) but it makes no sense because it should really be displaying whichever is the closest event. Tapping the main time will make it change to "57m until solar noon" which is the correct behaviour as it is the nearest event coming up.

This bug feels like only the main clock element is being called and refreshed and not the other 2 elements in tandem.

**Comment by forrestguice** [comment]
Thanks for the heads up. I'll take another look at this.

> This bug feels like only the main clock element is being called and refreshed and not the other 2 elements in tandem.

This probably true. The clock and the card are actually running separate loops (the clock every 3 seconds, and the card once a minute). The card is a RecyclerView (and each card its own ViewHolder), so the mechanism for updating needs to live within that architecture. I think there are situations where the card becomes "stopped" and by switching to another day it triggers a rebind (restarting the loop). It seems like a "lifecycle" issue exacerbated by leaving the app running for long periods of time.

I think the problem with the "note area" might be tangential. Its possible to swipe it forward/back, but then afterward its intentionally "locked" to that event. It does this to avoid automatically scrolling away (which can be very annoying). So it seems probable that area was "touched" at some point, and then remains locked (as long as the app is left open). I'm not sure how to fix this - maybe this calls for a small floating button to indicate its locked (and provide a way to restore it).

**Comment by Sunspark-007** [comment]
A small lock icon is an interesting idea, I didn't know it already was possible to lock an event, that's great to know.

So, an observation I made the other day about the sun position in relation to the card, as I kept scrolling to future days I noticed that on a bunch of the days it would show the outlined sun in its current position but after perhaps 5(?) days of scrolling it would show the sun in the "stuck" position of late in the evening and if you kept on scrolling, it would seem to loop in a pattern. So that tells me it is holding 2 values in memory, the current value and is applying one of them to a given day but not the others.

I am going to try an experiment, I turned off battery optimization to see how the card refresh is affected.

**Comment by forrestguice** [comment]
It sounds like there are actually 3 issues here :\

The last one sounds really familiar. I remember seeing something like this while testing.
When seeking to a date in the future (like a future equinox or solstice), the graph would fail to update and continued showing the current day. It was really obvious when the dates differed so much, but when its only a few days its easy to miss. I found the cause and fixed it though (or thought so) - a race condition was causing the graph to draw twice, once with the right date, and then again with the "wrong" one.

> I turned off battery optimization to see how the card refresh is affected.

It shouldn't make a difference. Its definitely needed to trigger alarms, but otherwise the app is entirely in the foreground. When the app is paused/resumed (no longer showing but still running) its loops/threads are paused too. They are supposed to resume when the app takes the foreground again. It doesn't sound like its happening correctly (a lifecycle issue causing the original issue).

**Comment by Sunspark-007** [comment]
Hm.. This thread might be a possible solution.. tho it does mean ditching RecyclerView in favour of LazyColumn and LazyRow: https://stackoverflow.com/questions/60765370/what-is-the-jetpack-compose-equivalent-of-recyclerview-or-listview

I don't like Jetpack Compose because I think it doesn't scroll graphics smoothly (in an app I use a lot, so I use an older version of it, but it could also just be inexperience on the part of the coders). However Suntimes doesn't need to be smooth-scrolling at all, and it might make things easier to switch to it since you said in the other thread you are going to have to change the min-api level anyway. Worth investigating!
