### ISSUE TITLE
Widget that "always" is on current location

### ISSUE THREAD

**Issue by lmamane** [forrestguice/SuntimesWidget#707]
I'd like to have a widget that is always on the current location, for some value of "always". Obviously for battery management reasons, "current location" could be refreshed only every 15min or 60min or whatever, and/or be opportunistically refreshed when another app asks for location anyway, and/or be refreshed only when the widget is actually displayed (phone not locked, and the launcher is on the page where the widget is). E.g. https://github.com/xxv/24hAnalogWidget seems to do that rather well.

I nearly get that now by creating a widget and checking "Use the app location" option, but this looks like I need to actively go into the app and refresh the location there so that the widget updated its location?

**Comment by forrestguice** [comment]
This would be a nice feature. 

I've considered it in the past, but stopped after encountering various technical challenges. It has been several years, but I remember there being limitations when running within an AppWidgetHost. I think to have the widget periodically update the location, it would be necessary to have it backed by some service (that performs those requests on its behalf).

I was curious how 24hAnalogWidget accomplishes [this](https://github.com/xxv/24hAnalogWidget/blob/5cda1d0e4adf287ce8d12b56bedb750796c32274/wear/src/main/java/info/staticfree/android/twentyfourhour/WearFace.java#LL111C59-L111C79), and its through the FusedLocationProvider. Unfortunately that is a "Google Play" [api](https://developer.android.com/training/location/retrieve-current), afaik closed source, and so unavailable to us. To get by without it, we're responsible for managing the location updates on our own.

> I nearly get that now by creating a widget and checking "Use the app location" option, but this looks like I need to actively go into the app and refresh the location there so that the widget updated its location?

That sounds right. The app makes all location requests in the foreground, so updating the "app location" requires launching it to trigger an update. That process queries the "gps", "network", or "passive" providers (everything except "fused") before falling back to the "last known". If the "Passive Location" option is enabled, then some other app is responsible for managing the locations requests in the background (e.g. SatStat).

I think a compromise might be to allow widgets to be configured to "current location" with the caveat that they are restricted to the passive provider. It would still be necessary to trigger location updates separately (but from any location aware app), and then the widget would follow on its next refresh.

**Comment by lmamane** [comment]
> I was curious how 24hAnalogWidget accomplishes [this](https://github.com/xxv/24hAnalogWidget/blob/5cda1d0e4adf287ce8d12b56bedb750796c32274/wear/src/main/java/info/staticfree/android/twentyfourhour/WearFace.java#LL111C59-L111C79), and its through the FusedLocationProvider. Unfortunately that is a "Google Play" [api](https://developer.android.com/training/location/retrieve-current), afaik closed source, and so unavailable to us. To get by without it, we're responsible for managing the location updates on our own.

24hAnalogWidget is available on F-Droid (that's where I got it from) and works correctly as far as I can observe on LineageOS, no Google Apps, no Google services, no substitute such as MicroG either.

**Comment by forrestguice** [comment]
hrm. I guess I'm reading from the wrong code then and `FusedLocationProvider` isn't used afterall, or maybe I'm mistaken about its licensing. I did find those references in the "wear" folder (which is another non-free api afaik).

The F-Droid description says "The widget passively accesses the phone's location and if it gets a fix..." which sounds like passive provider behavior to me. I'm not sure how that widget is initiating a location update on its own, but according to the description it isn't.

On another note, does your own location really change so frequently? The sunrise/sunset times for a region do not typically differ greatly - I leave the app configured to my local city center. Unless you are flying or driving somewhere every day, I'm not sure I fully understand the use-case.

**Comment by forrestguice** [comment]
btw, I'm a bit doubtful the 24AnalogWidget is still build-able by F-Droid. The [build recipe](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/info.staticfree.android.twentyfourhour.yml) is pretty basic (no mention of play apis), there appear to be libs included as [jars](https://github.com/xxv/24hAnalogWidget/tree/main/lib/libs), the [build log](https://f-droid.org/repo/info.staticfree.android.twentyfourhour_8.log.gz) is missing, and the binary was apparently produced in 2013? That may be something the F-Droid maintainers would be interested in knowing about or verifying. 

At any rate, the 24AnalogWidget appears to work fine, but I can't figure out where/how its getting the location. The only location related code appears alongside that other "wear" related stuff. I'm not really confident that isn't what F-Droid has compiled/shipped. Anyhow, the point here wasn't to audit some 10 year old app. Its just a curiosity, that's all. ;)

I think that widget is listening for the location passively - we should be able to do the same. :)
I think automatically refreshing the location every 15, or 30 minutes is out-of-scope though, as I'd rather not write my own location aware service, and apis that are part of playservices remain out of the question.

**Comment by forrestguice** [comment]
Mystery solved; here's [how it does it](https://github.com/xxv/24hAnalogWidget/blob/511f9ff6c166e331b60776d1950693066835ef18/src/info/staticfree/android/twentyfourhour/SunPositionOverlay.java#L68). It is using the passive provider.  We can definitely do the same.

It helps to look in the right place. 😓 Apparently code search via GitHub doesn't work within tags, and I've been searching the head of the repo this entire time (which contains a ton of unpublished (unrelated) changes). The version F-Droid has published is just fine. I do doubt they'd choose to (re)compile it today though (without doing something about that precompiled jar).

**Comment by lmamane** [comment]
> On another note, does your own location really change so frequently? (...) Unless you are flying or driving somewhere every day, I'm not sure I fully understand the use-case.

Not every day, but most months I have a few days where my location changes by several hundreds of km, often twice within the day, as I do mostly "day trips". And indeed that is through flying; I'm a recreational airplane pilot. Some aerodromes cannot be used after civil dusk ("at night"), and even if they do, I have to log time spent flying "at night" (defined by civil twilight) separately. Having the widget is convenient. FYI, I have two widgets, one set on my homebase and one which (after installing 0.15.4) will be on "current location".

Also, out of pure geek/nerd spirit, I enjoy my tools having precision far beyond what is actually useful; e.g. I enjoy that my watch is synchronising with atomic clocks and has very precise time, even though in practice in daily life minute-level accuracy (for "what time is it", not for measuring durations) is by far enough. I enjoy having, and using, precise electronic weighting scale that I can calibrate and measure the minute difference in mass of my watch before and after I cleaned the bracelet from the accumulated grime.

> At any rate, the 24hAnalogWidget appears to work fine, but I can't figure out where/how its getting the location. (...)
> 
> I think that widget is listening for the location passively - we should be able to do the same. :)

Experience shows that's good enough and I'm happy with that... probably because I tend to use a map app when in a new location, so the pocket computer gets a fix anyway.

Thanks!

**Comment by forrestguice** [comment]
Thank you. I like hearing what others are doing with the app.
That sounds like a very cool use for it!
