### ISSUE TITLE
widget list shows only one but home screen has two

### ISSUE THREAD

**Issue by lmamane** [forrestguice/SuntimesWidget#711]
I have two widgets on my launcher screen, but when I

1. Open SunTimes app
2. Tap on vertical '....'
3. Tap 'Settings'
4. Tap 'Widgets'

only one of them is shown. I would have expected all of them.

The two widgets differ only by location, and that one of them is configured as 3×1 and the other 2×1, although I admit I cannot see the difference in the result, nor do I understand how the second one was created as 3×1

**Version Info:**
 - App Version: 0.15.3 (d1ed79c4f)
 - Android Version: 13, LineageOS 20-2023-0530-NIGHTLY-lemonadep, build TQ2A.230505.002 34b7477262
 - Device Model: OnePlus 9 Pro - model LE2123

![IMG_20230603_082132](https://github.com/forrestguice/SuntimesWidget/assets/7558692/0d94aa58-13ff-4999-8aa2-aa79cad4cf76)
![Screenshot_20230603-082902_Suntimes-nq8](https://github.com/forrestguice/SuntimesWidget/assets/7558692/327440ef-6e58-42f4-8a91-cb6bf929f4ba)
![Screenshot_20230603-082847_Suntimes-nq8](https://github.com/forrestguice/SuntimesWidget/assets/7558692/46628092-fc78-433c-a8bb-cac959c3bfb1)
![Screenshot_20230603-083854_Suntimes-nq8](https://github.com/forrestguice/SuntimesWidget/assets/7558692/73eacf4c-e745-4461-8558-fde7fac84dbd)

**Comment by forrestguice** [comment]
Thanks. I notice a few issues here. They should be fixed in the next patch.

> The two widgets differ only by location, and that one of them is configured as 3×1 and the other 2×1, although I admit I cannot see the difference in the result, nor do I understand how the second one was created as 3×1

These are identical unless then "show solar noon" option is checked. Also, the previews are currently the same (3x1 preview is missing). That is probably how it ended up being created that way.

**Comment by JonnyTech** [comment]
I too had an issue where a 3x1 widget was not showing in the list, v0.15.4 fixed that. Thank you.
