### ISSUE TITLE
HijriMonth [Feature request] 

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#714]
hello @forrestguice ,

could you please add this as widget

http://time4j.net/javadoc-en/net/time4j/calendar/HijriMonth.html

thank you

**Comment by islam2hamy** [comment]
month name :
https://hijri.today/mnames.html

**Comment by forrestguice** [comment]
I've added http://time4j.net/javadoc-en/net/time4j/calendar/HijriCalendar.html to the "date widget".

It should be possible to use any of the `Calendar` classes from http://time4j.net/javadoc-en/net/time4j/calendar/package-summary.html. If calendars (or variants) are added there, we can add them here.

**Comment by islam2hamy** [comment]
Thank you
