### ISSUE TITLE
Some doubts during the translation update

### ISSUE THREAD

**Issue by naoliv** [forrestguice/SuntimesWidget#719]
Hi, @forrestguice!

I am finishing updating the pt_BR translation, but I have a doubt about the cross-quarter days.

For example, in the original string it's saying that:

https://github.com/forrestguice/SuntimesWidget/blob/d16bf4decec8e820e55dbb588663ad0e43454b8a/app/src/main/res/values/strings.xml#L2268

But isn't the midpoint between the Winter Solstice and Spring Equinox the Winter Cross-Quarter?

Or by reading this table (from https://www.hestiasmuse.net/post/the-wheel-of-the-year-quarters-and-cross-quarters) I am confusing it with what it calls as "Mid Winter"?

![](https://github.com/forrestguice/SuntimesWidget/assets/982338/eb5b3dcb-c0f8-4575-8d72-3e33a650969b)

**Comment by forrestguice** [comment]
> But isn't the midpoint between the Winter Solstice and Spring Equinox the Winter Cross-Quarter?

I don't believe so, but when researching this I didn't actually encounter phrases like "winter cross-quarter". Instead I encountered "cross quarter days", as well as the pagan labels, e.g. "Imbolc". I think the wording chosen by the app is unique (and might indeed be wrong), but I wanted to avoid using the pagan labels.

Imbolc, for example, is a traditional festival that celebrates the beginning of spring. It is technically "mid winter", but it is also the first day of the year when it might actually feel like spring, and for that reason I labeled it "Spring Cross-Quarter". Similar, "Beltane" is a festival that celebrates the coming of summer, but technically occurs mid-spring. So, it makes sense to me to call this the summer-cross quarter.

I have no idea if that's accurate or not, but labeling them the other way around makes less sense to me. e.g. the "winter cross-quarter" isn't about celebrating winter, its about the coming transition to spring.

**Comment by forrestguice** [comment]
I'm checking again, searching for these phrases. I'm finding both definitions. :\
It would be nice to reference something definitive.

**Comment by forrestguice** [comment]
Hrm. I'm going to switch these to the labels used in #551. They do imply some religious context, but in this case I think I'm ok with that.

Does "spring cross-quarter" mean the cross-quarter day in astronomical spring, or the cross-quarter day that signifies the start of spring.. I see it both ways, but I don't think it actually matters if the current label is right or wrong. Its ambiguous (sufficient reason to change it).

**Comment by naoliv** [comment]
Are mid spring, mid summer, mid fall and mid winter the same thing?
At least for me, these terms convey a simpler idea of the time of year we're in (for example, at a glance, it's intuitive to realize we're in the middle of spring).

**Comment by forrestguice** [comment]
That also works.

My own understanding of the seasons has changed a bit since learning about these. The midpoint of astronomical winter is the "true start" of spring, while spring equinox is its height. I like that it matches my personal experience (where summer temperatures arrive in May, not June). I now realize labeling it like this is source of confusion though. If the app refers to "spring" or "summer", it needs to be entirely within the context of the "astronomical seasons".

I went ahead and changed the labels from; "Spring Cross-Quarter" to "Imbolc (Cross-Quarter)", etc.

If you want to keep the translation simple, "Mid winter (Cross-Quarter)" is perfectly fine, or "February (Cross-Quarter)", or any variation. Unfortunately I've already "messed up" the string names throughout the project; e.g. `timeMode_cross_spring` refers to "mid winter".

**Comment by forrestguice** [comment]
I think "cross quarter" will need to be incorporated into the label somehow.
For example, there is also "Midsummer" (like "a midsummer night's dream"), but that has different meaning than "mid-summer (cross-quarter").

**Comment by naoliv** [comment]
"midpoint"? Like "Summer's midpoint"

**Comment by forrestguice** [comment]
I think that works too.
btw, there is similar confusion around "midwinter" too; https://en.wikipedia.org/wiki/Midwinter

> Beginning in the 18th century, the term midwinter has sometimes been misunderstood as synonymous with the winter solstice.[[4]](https://en.wikipedia.org/wiki/Midwinter#cite_note-FOOTNOTENordberg2006120%E2%80%93121-4)

I'm starting to actually like terms like "Imbolc", "Beltane", etc, as there's only a single meaning.

**Comment by naoliv** [comment]
Do you mind if I use a translation that, in English, would mean something along the lines of "Imbolc (mid-winter)"?

It seems that there isn't a very good translation for "cross-quarter," and I believe it might sound a bit odd to keep the original term in the translation (such as "Imbolc (Cross-Quarter)").

**Comment by forrestguice** [comment]
I leave that entirely at your discretion. 
My attitude is that translators own their translations.

My goal is to reduce confusion (because I'm realizing its very confusing), and avoid a situation where the app contributes to that.
