### ISSUE TITLE
Reference issue #22

### ISSUE THREAD

**Issue by svjasonmchristosthefirstsp** [forrestguice/SuntimesWidget#720]
[https://github.com/forrestguice/NaturalHour/issues/22#issuecomment-1624678371](https://github.com/forrestguice/NaturalHour/issues/22#issuecomment-1624678371)

**Comment by forrestguice** [comment]
I plan to track this bug in the other issue. 
These two apps do interact (and that is frequently a source of bugs), but in this case I think the problem resides in "Natural Hour".
