### ISSUE TITLE
[Feature request] High brightness alarms

### ISSUE THREAD

**Issue by foxjaw** [forrestguice/SuntimesWidget#741]
Alarms with Light mode (White background) with high brightness. Possible to max the brightness on alarm interface ?
This is very effective. Just try yourself by changing the app theme into light mode, & manually set phone brightness to high before bedtime. See how fast you'll wake up !

**Comment by forrestguice** [comment]
You will need to toggle `Settings -> Alarms -> Fullscreen -> Bright Alarms" to enable it. 

I think the feature is still rough around the edges, so it will probably see some improvements in upcoming patches.

**Comment by forrestguice** [comment]
Oh dang. You are right, its not there. 
The definition is missing on Android 14.
