### ISSUE TITLE
Very big font size for date widget

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#763]
**Describe the bug**
Very big font size for date widget

**To Reproduce**
1. Add date widget
2. Chnge format as in Screenshot

**Expected behavior**
best fit , small font size widget

**Screenshots**
![IMG_٢٠٢٤٠١٢٥_٠٥٢٢٥٠](https://github.com/forrestguice/SuntimesWidget/assets/7989030/434aeb00-6932-4326-a7b1-8d43abd09394)

**Version Info:**
 - App Version: 0.15.10
 - Android Version: 14
 - Device Model: Redmi Note 12

**Comment by forrestguice** [comment]
`v0.15.11` changes the way the text scaling is implemented.
It fixes other bugs I've observed, so it might fix this problem too.

After testing (sometime next week), please post a comparison screenshot, and reopen the issue if its not fixed.


 - please post a screenshot for comparison

**Comment by islam2hamy** [comment]
Thank You

**Comment by islam2hamy** [comment]
Not fixed with all formats :(

**Comment by islam2hamy** [comment]
Ps. Using kiss launcher

**Comment by forrestguice** [comment]
Well that's a shame :\ 
With the recent implementation, the scaling look better to me, but I'm mostly testing in English (with a left-to-right layout).
I suspect these are contributing factors that I'll need to explore.

Which patterns specifically are broken? 
Are there other patterns that actually seem improved or have changed?

Please list out each "date pattern" (text appearing below the "date format"), with a screenshot if possible. 
I'll try and reproduce the problem more closely.

**Comment by islam2hamy** [comment]
no problem bro

![IMG_٢٠٢٤٠٢١٣_٢٠٥٨٥٦](https://github.com/forrestguice/SuntimesWidget/assets/7989030/a6e52597-d1dd-42ec-b683-76380dde9ee0)
![IMG_٢٠٢٤٠٢١٣_٢٠٥٧١٣](https://github.com/forrestguice/SuntimesWidget/assets/7989030/f5e4470d-f850-4899-97a9-903aee60db2d)
![IMG_٢٠٢٤٠٢١٣_٢٠٥٦٥٧](https://github.com/forrestguice/SuntimesWidget/assets/7989030/a2422ec9-08c5-4397-9d04-54212aa816fd)

**Comment by forrestguice** [comment]
Hopefully this is actually fixed.
I couldn't reproduce it exactly, but on a hunch enabled a developer setting that draws the margins/paddings as lines. Afterward I noticed the text was slightly offset by a few pixels instead of centered. Examining your second screenshot, the text actually looks like its the correct size, but its also offset from center (by a lot!). Anyhow, the layout was refactored.

**Comment by islam2hamy** [comment]
Fixed 
Thank you
