### ISSUE TITLE
[Feature request] Current location for alarm

### ISSUE THREAD

**Issue by bryankaplan** [forrestguice/SuntimesWidget#768]
I'd like to create an alarm, the location for which is "current location", which automatically updates as I travel.

Is that already possible somehow?

**Comment by forrestguice** [comment]
It isn't currently possible, but that does sound like a very interesting feature. 👍

**Comment by bryankaplan** [comment]
Thank you. I think the terminology could be improved. Maybe "variable location"? I'm not sure. But "current location" sounds too constant. "Mobile location"?

**Comment by bryankaplan** [comment]
@forrestguice Thank you!
