### ISSUE TITLE
[Feature request] please make a github build of the latest 0.6.1 calendar plug in 

### ISSUE THREAD

**Issue by topcaser** [forrestguice/SuntimesWidget#776]
Hi, did you accidentally miss a github release of the latest 0.6.1 calendar plug in? It's not in the asset section...

**Comment by forrestguice** [comment]
I might have mentioned in #771, but Suntimes Calendars is also built and signed by F-Droid.
I was copying those binaries to GitHub Releases for convenience, but recently decided to stop.

Instead the apks are available from their own "Suntimes Apps" repo (#772) if an alternate download is needed.
Getting it directly from the main F-Droid repo is still the quickest way to learn about updates though.
