### ISSUE TITLE
Suntimes Event Alarm error is Moon Phase alarm repeat. 

### ISSUE THREAD

**Issue by MyHeadHurtsNow** [forrestguice/SuntimesWidget#803]
**Describe the bug**
I set an alarm for today's New Moon as an Event, which fired off on time and as set. But, the auto repeat showed the Next New Moon to be August 4th, 2024 @ 12:13 hrs BST, which is 58d 22hrs ahead. This is incorrect. The next new moon is actually July 5th,  23:57 BST

**To Reproduce**
1. Day before the next New Moon, create a new alarm in Suntimes Alarm App
2. Choose "New Moon" from the Event drop down menu 
3. Save alarm, and close Suntimes Alarm app
4. Let alarm go off the next day as scheduled and dismiss. 
5. Open up Suntimes Alarm app and check the next scheduled New Moon Event Alarm. You will see the error, where it has skipped 

**Expected behavior**
The next scheduled New Moon Event alarm should be at the date and time of the next New Moon as calculated on Suntimes app, which is approximately 29 days ahead

**Screenshots**
Screenshots attached 
1. ![Screenshot_20240606_141847_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/170753567/63aaa253-0a95-43af-ad62-88b44ad38190)
2. ![Screenshot_20240606_141746_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/170753567/e43461bc-3485-42e0-b9b8-6c2110005372)
3. ![Screenshot_20240606_142239_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/170753567/9bfe1193-772c-4cf0-ab4a-2baf7ddefb7e)

**Version Info:**
 - App Version: [ 0.15.15]
 - Android Version: [ 14]
 - Device Model: [Samsung Galaxy A13 model SM-A137F/DSN]

**Additional context**
Add any other information about the problem here.

**Comment by forrestguice** [comment]
Thanks for the detailed report. 👍 
I was able to reproduce this bug, so likely it will be fixed soon.

**Comment by MyHeadHurtsNow** [comment]
You're welcome.
Thanks. 👍
