### ISSUE TITLE
[Bug Report] "Sun Position" screen altitude has the wrong colour during Nautical/Astronomical Twilight

### ISSUE THREAD

**Issue by elydpg** [forrestguice/SuntimesWidget#805]
**Describe the bug**
Pretty much the title

**To Reproduce**
1. Open the app and click on "Sun Position" from the hamburger menu. Make sure the current location has nautical and astronomical twilight
2. Advance until the altitude is between -6 and -12 degrees
3. Note the colour of the altitude text
4. Advance until the altitude is between -12 and -18 degrees
5. Note the colour of the altitude text

**Expected behavior**
Altitude text should be medium blue between -6 and -12 degrees and dark blue between -12 and -18 degrees

**Screenshots**

Civil Twilight (working as intended):

![Screenshot_20240612-200845_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/8622264/e5e727fe-536e-4770-b7b0-6f131edfad59)

Nautical Twilight

![Screenshot_20240612-200910_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/8622264/df506898-4b39-41bb-b7f4-5dbad2c99fce)

Astronomical Twilight

![Screenshot_20240612-200921_Suntimes](https://github.com/forrestguice/SuntimesWidget/assets/8622264/0d0bcc05-25df-444b-982c-1d124fff90de)

**Version Info:**
 - App Version: 0.15.15
 - Android Version: 12
 - Device Model: Samsung Galaxy s10e

**Comment by forrestguice** [comment]
IIRC, it was originally as you described, but the contrast of the nautical/astronomical colors was very poor. The quick fix at the time was to replace these colors (with gray) to make it readable.

I plan to make the colors consistent again in `v0.16.0`. 
I think to fix contrast issues, it will underline the field in a given color instead.
