### ISSUE TITLE
[Feature request] Update alarms automatically on location change 

### ISSUE THREAD

**Issue by Friptick** [forrestguice/SuntimesWidget#808]
Hello! This is to report a slight UX annoyance in your amazing app.

To reproduce:

1. Let's say I have an alarm (or quick notification) set for dawn at **Last position**
2. I take the train 400km to the east!
3. Open Suntimes, it gets the new location automatically (on startup, this is a setting), everything is correct
4. **Next morning, my dawn alarm goes off 15 minutes too late!**

To prevent this situation, I need to remember, each time I change location, to go into the alarm, get the new location manually, and re-save the alarm.

Would it be possible to automatically update any position-relative alarms and notifications each time a new location is fetched?

Thanks for your work.

**Comment by forrestguice** [comment]
👍  I'm adding a "use app location" option to alarms in `v0.16.0`, so whenever that location changed, those alarms will get rescheduled.

#768

**Comment by Friptick** [comment]
Great work @forrestguice
