### ISSUE TITLE
Allow at least custom locations deletion

### ISSUE THREAD

**Issue by bugith** [forrestguice/SuntimesWidget#809]
Hi 

I mistyped twice a new custom location. Unfortunately I could not find any rename or delete button.

Please add this so that we can delete and rename the selected entry.
Best regards

**Comment by forrestguice** [comment]
It isn't currently possible from the selection dialog, but I agree a delete action would be very useful there.

It should be possible to delete from the "places activity", which is an extra click or two away.
https://forrestguice.codeberg.page/Suntimes/help/more/places/manageplaces/#copy-edit-remove

There's an unusual bug here though. Each widget/alarm maintains its own configuration and automatically adds that location to the list, so if there is a typo in the name somewhere, it might keep reappearing after you delete it. In that case you'll need to reconfigure or delete each of those widget/alarms too (and then remove the place).

**Comment by bugith** [comment]
Thank you, I didn't see the Settings/Places path.
Lovely App !
