### ISSUE TITLE
Seeking timeforge library sourcecode 

### ISSUE THREAD

**Issue by HolyNameSoftware** [forrestguice/SuntimesWidget#815]
Is this https://github.com/MenoData/Time4J the source of the same lib Suntimes app uses? It seems old referencing java 8.

**Comment by forrestguice** [comment]
> Is this https://github.com/MenoData/Time4J the source of the same lib Suntimes app uses?

Yes. It is linked right there in the README, and also from within the app itself.

> It seems old referencing java 8.

Yes.

**Comment by HolyNameSoftware** [comment]
Perhaps this may clarify to you what I am focused on: [https://github.com/CruiserOne/Astrolog/issues/22](https://github.com/CruiserOne/Astrolog/issues/22)
