### ISSUE TITLE
JCenter is closing

### ISSUE THREAD

**Issue by licaon-kter** [forrestguice/SuntimesWidget#825]
ref: https://jfrog.com/blog/jcenter-sunset/

ref: https://github.com/forrestguice/SuntimesWidget/blob/v0.16.1/build.gradle#L19

ref: https://github.com/forrestguice/SuntimesWidget/blob/v0.16.1/app/build.gradle#L70 maybe update to `2.2.0` from Maven Central, see https://github.com/jraska/Falcon/issues/52#issuecomment-847395206

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7627873201#L2074

**Comment by licaon-kter** [comment]
for F-Droid we just remove the dep as it's used only in testing: https://gitlab.com/fdroid/fdroiddata/-/commit/b262a8c008c7cba7da533e3669ee0384d12a6484

**Comment by forrestguice** [comment]
thank you ❤️
