### ISSUE TITLE
lunar midnight is late into the morning

### ISSUE THREAD

**Issue by HoodBlah** [forrestguice/SuntimesWidget#827]
**Describe the bug**
When I select the lunar midnight option for my alarm it sets the time to late in the morning around 10am, but on Google lunar midnight it around 4am in my area

**To Reproduce**
1. Go to 'alarms'
2. Click on 'lunarmidnight'
3. See it say '10am'

**Expected behavior**
Lunar midnight should be around 4am.

**Screenshots**
![Screenshot_20240913_113713_Suntimes](https://github.com/user-attachments/assets/da08b41f-fae4-4b23-9821-a93110fec227)

**Version Info:**
 - App Version: [e.g. 0.16.1]
 - Android Version: [e.g. 14]
 - Device Model: [e.g. Galaxy S23+]

**Additional context**
Add any other information about the problem here.

**Comment by forrestguice** [comment]
Yes, that's possible. Incidentally you actually aren't the first to ask, which I think is an indication that the UX could be improved.

From the "edit alarm" screen, either tap the `at` button (under `schedule`), or from the overflow menu `: -> Options -> Set Offset (before/after)`. Then from the "alarm list", `: -> Sort -> Show Offsets` toggles whether the "offset" is show separately or combined.

**Comment by HoodBlah** [comment]
Nice! I just set up an alarm using a -3hr offset and the only real complain I have is that it shows the time of the timesetting but just add -3hr before on top of it instead of what the actual time would be. I need to open the alarm and then tap the time in order to see when it'd actually go off. Quick math's is fine but it's a bit tedious especially if you are doing minutes and stuff.
