### ISSUE TITLE
Boot Completed hangs after phone restart

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/SuntimesWidget#842]
**Describe the bug**
Boot Completed hangs after phone restart

**To Reproduce**
1. Set alarm
2. Restart the phone
3. Boot Completed notification and the app hangs

**Version Info:**
 - App Version: 0.16.3
 - Android Version: 14
 - Device Model: Readmi note 12

**Comment by forrestguice** [comment]
I'm not sure I understand what you mean by "hangs". Can you help clarify.
Does it "ANR" (application not responding) with the OS showing a dialog box? Or is it more like the notification is shown, and then fails to automatically dismiss? When you restart the phone, does all this happen before it is initially unlocked? What happens if tested with v0.16.2 - is it recently introduced?

**Comment by forrestguice** [comment]
Also, what happens if you trigger "Boot Completed" from settings; `Settings -> Alarms -> Boot Completed`? 
Does this also result in a "hang"?

**Comment by islam2hamy** [comment]
> notification is shown, and then fails to automatically dismiss?

Yes , and application not responding

>When you restart the phone, does all this happen before it is initially unlocked? 

No , after

>What happens if tested with v0.16.2 - is it recently introduced?

No , working good with v0.16.2

**Comment by islam2hamy** [comment]
> Also, what happens if you trigger "Boot Completed" from settings; `Settings -> Alarms -> Boot Completed`? Does this also result in a "hang"?

No , working good

**Comment by forrestguice** [comment]
I'm able to reproduce it finally (after trying for maybe 20 minutes).

It is somehow related to addon alarms; everything tested normal until I added a "natural hour" alarm. After rebooting and unlocking I see the notification indefinitely, and clicking it opens to a black screen (application not responding).

I'm not sure why `v0.16.3` would act this way though. 😕
