### ISSUE TITLE
configuration: set the lat / lon from street address

### ISSUE THREAD

**Issue by forrestguice** [forrestguice/SuntimesWidget#9]
SettingsActivity feature; enabled for "custom location" mode.

Add a button that allows setting the latitude/longitude to a location determined by street address (geocode address -> set lat/lon on UI -> toast).

**Comment by HerHde** [comment]
How about [OSM Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) for this job?

**Comment by forrestguice** [comment]
hrm, that looks very interesting. I wasn't aware of that. it would require adding network permissions though, which I really don't want. 

an offline library would be better but I think that means an increase of 7 or 8mb just to keep a limited db of cities. 

it would be ideal if I could just delegate this to another app w/ an intent. there is no general intent that I'm aware of (outside of using google's own "FusedLocationProvider" which is a gplay thing). maybe there is something on fdroid that already does this (and exposes it via Intent). if not I think this feature is out.

**Comment by forrestguice** [comment]
I'm going to close this - there are some apps on fdroid that can do this then share the location - the suntimes app already handles the geo intent and opens the "set location" dialog. 

I just tried Acastus and the integration was pretty nice, so I don't really see a need any more.
